<?php
require __DIR__.'/../vendor/autoload.php';
$app=require __DIR__.'/../bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
if (!app()->environment('local')) throw new RuntimeException('Local test only');
use App\Models\User;
use App\Models\Plan;
use App\Models\Order;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
require __DIR__.'/fixtures/V10TestPayment.php';
Illuminate\Support\Facades\Queue::fake();
config(['v2board.telegram_bot_enable'=>0,'v2board.ticket_status'=>0]);
$cleanupUsers=[];
$checks=0;
set_exception_handler(function($e) { fwrite(STDERR,$e->getMessage()."\n"); exit(1); });
$assert=function($ok,$label) use (&$checks) { if (!$ok) throw new RuntimeException($label); $checks++; };
$call=function($method,$path,$body=[],$token=null,$language='en-US',$extra=[]) use ($app) {
    $server=['HTTP_ACCEPT'=>'application/json','HTTP_ACCEPT_LANGUAGE'=>$language,'HTTP_USER_AGENT'=>'V10ContractTest','CONTENT_TYPE'=>'application/json'];
    $server=array_merge($server,$extra);
    if ($token) $server['HTTP_AUTHORIZATION']=$token;
    $r=Illuminate\Http\Request::create($path,$method,[] ,[],[],$server,$method === 'GET' ? null : json_encode($body));
    $app->instance('request',$r);
    $response=$app->make(Illuminate\Contracts\Http\Kernel::class)->handle($r);
    return [$response,json_decode($response->getContent(),true)];
};
DB::beginTransaction();
try {
    $plan=Plan::create(['name'=>'V10 test','group_id'=>1,'transfer_enable'=>50,'month_price'=>1000,'year_price'=>9000,'show'=>1,'renew'=>1]);
    $user=User::create(['email'=>Str::uuid().'@example.com','password'=>password_hash('V10testpassword',PASSWORD_DEFAULT),'token'=>Str::random(32),'uuid'=>(string)Str::uuid(),'balance'=>1500,'transfer_enable'=>0,'expired_at'=>0]);
    $cleanupUsers[]=$user;
    $credentials=(new App\Services\AuthService($user))->generateAuthData(Illuminate\Http\Request::create('/'));
    $bearer='Bearer '.$credentials['auth_data'];
    config(['v2board.recaptcha_enable'=>0]);
    [$r,$j]=$call('POST','/api/v10/auth/sessions',['email'=>$user->email,'password'=>'V10testpassword','language'=>'en-US']);
    $assert($r->getStatusCode()===200 && $j['data']['tokenType']==='Bearer' && isset($j['data']['expiresAt']) && App\Services\AuthService::decryptAuthData($j['data']['accessToken']),'Login resource '.json_encode($j));
    [$r,$j]=$call('POST','/api/v10/auth/sessions',['email'=>$user->email,'password'=>'InvalidPassword']);
    $assert($r->getStatusCode()===401 && $r->headers->get('WWW-Authenticate')==='Bearer','Invalid login uses 401');
    [$r,$j]=$call('GET','/api/v10/me');
    $assert($r->getStatusCode()===401 && $j['code']==='UNAUTHENTICATED','Missing authentication');
    $assert(str_contains($r->headers->get('Content-Type'),'application/problem+json') && isset($j['requestId']),'Problem contract');
    [$r,$j]=$call('GET','/api/v10/me?auth_data='.urlencode($credentials['auth_data']));
    $assert($r->getStatusCode()===401,'Query credential rejected');
    [$r,$j]=$call('GET','/api/v10/me',[],$bearer);
    $assert($r->getStatusCode()===200 && $j['data']['email']===$user->email && !isset($j['data']['password']),'Account resource');
    $assert($r->headers->get('Content-Language')==='en-US','Language negotiation');
    [$r,$j]=$call('GET','/api/v1/user/info',[],$credentials['auth_data']);
    $assert($r->getStatusCode()===200 && $j['data']['email']===$user->email,'Legacy account interoperability');
    [$r,$j]=$call('GET','/api/v10/plans',[],$bearer);
    $row=collect($j['data'])->firstWhere('id',$plan->id);
    $assert($r->getStatusCode()===200 && $row['quotaBytes']===50*1073741824 && $row['monthlyPrice']===1000,'Plan schema and byte units');
    [$r,$j]=$call('GET','/api/v10/plans/'.$plan->id,[],$bearer);
    $assert($r->getStatusCode()===200 && $j['data']['id']===$plan->id,'Plan detail resource');
    [$r,$j]=$call('POST','/api/v10/me/orders',['planId'=>$plan->id,'billingPeriod'=>'monthly','user'=>['id'=>1]],$bearer);
    $assert($r->getStatusCode()===201 && isset($j['data']['orderNumber']),'Order created '.json_encode($j));
    $old=$j['data']['orderNumber'];
    $assert(Order::where('trade_no',$old)->value('user_id')===$user->id,'Body cannot override ownership');
    [$r,$j]=$call('POST','/api/v10/me/orders',['planId'=>$plan->id,'billingPeriod'=>'annual','replacementOrderNumber'=>$old],$bearer);
    $assert($r->getStatusCode()===201 && Order::where('trade_no',$old)->value('status')===2,'Atomic order replacement '.json_encode($j));
    $new=$j['data']['orderNumber'];
    $other=User::create(['email'=>Str::uuid().'@example.com','password'=>'x','token'=>Str::random(32),'uuid'=>(string)Str::uuid()]);
    $cleanupUsers[]=$other;
    $otherAuth=(new App\Services\AuthService($other))->generateAuthData(Illuminate\Http\Request::create('/'));
    [$r,$j]=$call('GET','/api/v10/me/orders/'.$new,[],'Bearer '.$otherAuth['auth_data']);
    $assert($r->getStatusCode()===404,'Order ownership is enforced');
    [$r,$j]=$call('GET','/api/v10/me/orders?pageSize=1',[],$bearer);
    $assert($r->getStatusCode()===200 && count($j['data'])===1 && $j['meta']['pagination']['total']>=2 && $j['meta']['pagination']['pageSize']===1,'Pagination contract');
    [$r,$j]=$call('GET','/api/v10/me/orders/'.$new,[],$bearer);
    $assert($r->getStatusCode()===200 && $j['data']['status']==='unpaid' && $j['data']['billingPeriod']==='annual','Order enum contract');
    [$r,$j]=$call('POST','/api/v10/me/orders/'.$new.'/cancellation',[],$bearer);
    $assert($r->getStatusCode()===204 && Order::where('trade_no',$new)->value('status')===2,'Order cancellation');
    [$r,$j]=$call('GET','/api/v10/me/orders?pageSize=101',[],$bearer);
    $assert($r->getStatusCode()===422,'Page limit');
    [$r,$j]=$call('POST','/api/v10/auth/session-exchanges?verificationToken=query-secret');
    $assert($r->getStatusCode()===422,'Session exchange credentials are body-only');
    [$r,$j]=$call('POST','/api/v10/auth/sessions',['email'=>'invalid']);
    $assert($r->getStatusCode()===422 && isset($j['errors']['email']),'Form validation');
    [$r,$j]=$call('GET','/api/v10/subscriptions/not-a-token?format=invalid');
    $assert($r->getStatusCode()===422,'Subscription format allowlist');
    [$r,$j]=$call('GET','/api/v10/me/subscription',[],$bearer);
    $assert($r->getStatusCode()===200 && str_contains($j['data']['subscriptionUrl'],'/api/v10/subscriptions/'),'New subscription link '.json_encode($j));
    config(['v2board.subscribe_path'=>'/custom-subscription']);
    [$r,$j]=$call('GET','/api/v10/me/subscription',[],$bearer);
    $assert(str_contains($j['data']['subscriptionUrl'],'/custom-subscription?token='),'Custom subscription path is preserved');
    config(['v2board.subscribe_path'=>'/api/v1/client/subscribe']);
    [$r,$j]=$call('GET','/api/v10/subscriptions/'.$user->token.'?format=sing-box');
    $assert($r->getStatusCode()===200 && !isset($j['data']) && isset($j['outbounds']),'Native subscription configuration '.json_encode($j));
    [$r,$j]=$call('GET','/api/v1/client/subscribe?token='.$user->token.'&flag=sing');
    $assert($r->getStatusCode()===200 && isset($j['outbounds']),'Old subscription remains usable');
    $user->language='zh-TW'; $user->save();
    foreach ([''=>'zh-TW','en-US'=>'en-US','unsupported'=>'zh-TW'] as $header=>$expected) {
        [$r,$j]=$call('GET','/api/v10/subscriptions/'.$user->token.'?format=sing-box',[],null,$header);
        $assert($r->getStatusCode()===200 && $r->headers->get('Content-Language')===$expected,'Subscription language fallback: '.$header);
    }
    [$r,$j]=$call('GET','/api/v10/subscriptions/'.$user->token.'?format=sing-box&language=ja-JP',[],null,'en-US');
    $assert($r->headers->get('Content-Language')==='ja-JP','Explicit import language takes precedence');
    foreach (['clash','clash-meta','clash-verge','flclash','shadowrocket','surge','quantumult-x','stash','general'] as $format) {
        [$r,$j]=$call('GET','/api/v10/subscriptions/'.$user->token.'?format='.$format);
        $assert($r->getStatusCode()===200 && strlen($r->getContent())>0 && !isset($j['data']),'Native format '.$format.' status '.$r->getStatusCode().' '.substr($r->getContent(),0,300));
    }
    foreach ([1,2] as $mode) {
        config(['v2board.show_subscribe_method'=>$mode]);
        [$r,$j]=$call('GET','/api/v10/me/subscription',[],$bearer);
        $link=$j['data']['subscriptionUrl'];
        $subscriptionToken=basename(parse_url($link,PHP_URL_PATH));
        [$r,$j]=$call('GET',$link.'?format=sing-box');
        $assert($r->getStatusCode()===200 && isset($j['outbounds']),'Generated subscription credential mode '.$mode);
        Illuminate\Support\Facades\Cache::forget('totp_'.$subscriptionToken);
    }
    config(['v2board.show_subscribe_method'=>0]);
    [$r,$j]=$call('GET','/api/v10/no-such-resource');
    $assert($r->getStatusCode()===404 && !isset($j['trace']) && !isset($j['file']),'No debug internals in errors');
    [$r,$j]=$call('OPTIONS','/api/v10/me');
    $assert($r->getStatusCode()===204 && str_contains($r->headers->get('Access-Control-Allow-Methods'),'PATCH'),'CORS preflight');
    foreach (['me/summary','me/session','me/sessions','me/referrals','me/commissions','me/invitations','me/tickets','me/nodes','me/traffic-records','me/notifications','announcements','knowledge-articles','knowledge-categories','me/usage-resets','me/preferences/options','credit-packages','public/banners?placement=dashboard','public/settings','payment-methods'] as $path) {
        [$r,$j]=$call('GET','/api/v10/'.$path,[],$bearer);
        $assert($r->getStatusCode()===200 && array_key_exists('data',$j), 'Read resource '.$path.' '.json_encode($j));
    }
    [$r,$j]=$call('POST','/api/v10/me/tickets',['subject'=>'V10 support','priority'=>'high','message'=>'Local test message'],$bearer);
    $assert($r->getStatusCode()===201 && $j['data']['priority']==='high' && $j['data']['id']>0,'Ticket creation '.json_encode($j));
    $ticketId=$j['data']['id'];
    [$r,$j]=$call('GET','/api/v10/me/tickets/'.$ticketId,[],$bearer);
    $assert($r->getStatusCode()===200 && $j['data']['messages'][0]['mine']===true,'Ticket message resource');
    [$r,$j]=$call('GET','/api/v10/me/tickets/'.$ticketId,[],'Bearer '.$otherAuth['auth_data']);
    $assert($r->getStatusCode()===404,'Ticket owner cannot be bypassed');
    [$r,$j]=$call('POST','/api/v10/me/tickets',['subject'=>'Duplicate','priority'=>'normal','message'=>'Local test'],$bearer);
    $assert($r->getStatusCode()===409,'Unresolved ticket conflict '.json_encode($j));
    App\Models\TicketMessage::create(['user_id'=>$other->id,'ticket_id'=>$ticketId,'message'=>'Staff fixture reply']);
    [$r,$j]=$call('POST','/api/v10/me/tickets/'.$ticketId.'/messages',['message'=>'Thank you'],$bearer);
    $assert($r->getStatusCode()===204,'Ticket reply');
    [$r,$j]=$call('POST','/api/v10/me/tickets/'.$ticketId.'/closure',[],$bearer);
    $assert($r->getStatusCode()===204,'Ticket closure');
    [$r,$j]=$call('POST','/api/v10/me/usage-resets/consumptions',['requestKey'=>(string)Str::uuid()],$bearer);
    $assert($r->getStatusCode()===422 && isset($j['code']) && $j['status']===422,'Shared service response exceptions preserve 422 '.json_encode($j));
    $payment=App\Models\Payment::create(['uuid'=>Str::random(16),'payment'=>'V10TestPayment','name'=>'Local test provider','config'=>[],'enable'=>1]);
    $order=Order::create(['user_id'=>$user->id,'plan_id'=>$plan->id,'period'=>'month_price','trade_no'=>'v10-'.Str::random(16),'total_amount'=>1000,'status'=>0,'type'=>1]);
    $payment->handling_fee_percent=2; $payment->handling_fee_fixed=30; $payment->save();
    [$r,$j]=$call('POST','/api/v10/me/orders/'.$order->trade_no.'/payments',['paymentMethodId'=>$payment->id,'paymentToken'=>'test-card-token'],$bearer);
    $assert($r->getStatusCode()===200 && $j['data']['kind']==='redirect','Checkout redirect contract '.json_encode($j));
    $assert((int)App\Payments\V10TestPayment::$lastOrder['total_amount']===1050 && App\Payments\V10TestPayment::$lastOrder['stripe_token']==='test-card-token','Checkout fee and payment token reach provider');
    $assert($order->fresh()->payment_id===$payment->id && $order->fresh()->handling_amount===50 && $order->fresh()->status===0,'Checkout persists fee without prematurely activating');
    $notifyBody=['signature'=>'local-test-signature','orderNumber'=>$order->trade_no];
    [$r,$j]=$call('POST','/api/v10/webhooks/payments/V10TestPayment/'.$payment->uuid,$notifyBody);
    $assert($r->getStatusCode()===200 && $r->getContent()==='success' && $order->fresh()->status===1,'Native payment callback');
    [$r,$j]=$call('POST','/api/v1/guest/payment/notify/V10TestPayment/'.$payment->uuid,$notifyBody);
    $assert($r->getStatusCode()===200 && $r->getContent()==='success','Historical payment callback remains supported');
    $assert(Illuminate\Support\Facades\Queue::pushed(App\Jobs\OrderHandleJob::class)->count()===1,'Duplicate callbacks do not enqueue repeated activation');
    Illuminate\Support\Facades\Queue::pushed(App\Jobs\OrderHandleJob::class)->first()->handle();
    $expiry=$user->fresh()->expired_at;
    $assert($order->fresh()->status===3 && $user->fresh()->plan_id===$plan->id && $expiry>time(),'Payment provisions shared entitlement');
    [$r,$j]=$call('POST','/api/v10/webhooks/payments/V10TestPayment/'.$payment->uuid,$notifyBody);
    $assert($user->fresh()->expired_at===$expiry && Illuminate\Support\Facades\Queue::pushed(App\Jobs\OrderHandleJob::class)->count()===1,'Completed callback does not extend subscription twice');
    (new App\Jobs\OrderHandleJob($order->trade_no))->handle();
    $assert($user->fresh()->expired_at===$expiry,'Duplicate activation jobs are idempotent');
    [$r,$j]=$call('GET','/api/v10/me/orders/'.$order->trade_no.'/status',[],$bearer);
    $assert($r->getStatusCode()===200 && $j['data']['status']==='completed','Payment polling returns completed state '.json_encode($j));
    [$r,$j]=$call('POST','/api/v10/me/orders/'.$order->trade_no.'/payments',['paymentMethodId'=>$payment->id],$bearer);
    $assert($r->getStatusCode()===409,'Completed orders cannot be paid again');
    $free=Order::create(['user_id'=>$user->id,'plan_id'=>$plan->id,'period'=>'month_price','trade_no'=>'v10-'.Str::random(16),'total_amount'=>0,'status'=>0,'type'=>2]);
    [$r,$j]=$call('POST','/api/v10/me/orders/'.$free->trade_no.'/payments',['paymentMethodId'=>0],$bearer);
    $assert($r->getStatusCode()===200 && $j['data']['kind']==='confirmed' && $free->fresh()->status===1,'Zero-amount checkout '.json_encode($j));
    [$r,$j]=$call('GET','/api/v10/webhooks/payments/V10TestPayment/'.$payment->uuid.'?'.http_build_query(['signature'=>'local-test-signature','orderNumber'=>$old]));
    $assert($r->getStatusCode()===200 && $r->getContent()==='success' && Order::where('trade_no',$old)->value('status')===2,'Late GET callback cannot activate replaced order');
    [$r,$j]=$call('POST','/api/v10/webhooks/payments/V10TestPayment/'.$payment->uuid,['signature'=>'invalid','orderNumber'=>$order->trade_no]);
    $assert($r->getStatusCode()>=400 && $r->getContent()==='fail','Invalid provider signature uses native failure');
    $gateway=(new App\Services\PaymentService('V10TestPayment',$payment->id))->pay(['trade_no'=>$order->trade_no,'total_amount'=>1000,'user_id'=>$user->id,'stripe_token'=>null]);
    $assert(str_contains($gateway['data'],'/api/v10/webhooks/payments/'),'Newly generated callback URL');
    config(['v2board.app_url'=>'https://example.com','v2board.stop_register'=>0,'v2board.email_whitelist_enable'=>0,'v2board.email_gmail_limit_enable'=>0,'v2board.invite_force'=>1,'v2board.email_verify'=>1,'v2board.try_out_plan_id'=>0]);
    $email=Str::uuid().'@example.com';
    [$r,$j]=$call('POST','/api/v10/me/invitations',['email'=>$email],$bearer);
    $assert($r->getStatusCode()===202 && $j['data']['status']==='queued' && isset($j['meta']['taskId']),'Invitation queue resource '.json_encode($j));
    $invitationJob=Illuminate\Support\Facades\Queue::pushed(App\Jobs\SendInvitationEmailJob::class)->last();
    Illuminate\Support\Facades\RateLimiter::clear('127.0.0.1');
    [$r,$j]=$call('POST','/api/v10/auth/email-verifications',['email'=>$email,'invitation'=>$invitationJob->token,'resetPassword'=>false]);
    $assert($r->getStatusCode()===202 && $j['data']['status']==='queued','OTP queued asynchronously '.json_encode($j));
    $assert(Illuminate\Support\Facades\Queue::pushed(App\Jobs\SendEmailJob::class)->last()->queue==='send_email_priority','OTP remains on dedicated priority queue');
    $code=Illuminate\Support\Facades\Cache::get(App\Utils\CacheKey::get('EMAIL_VERIFY_CODE',$email));
    [$r,$j]=$call('POST','/api/v10/auth/registrations',['email'=>$email,'password'=>'V10newpassword','emailCode'=>$code,'invitation'=>$invitationJob->token,'language'=>'zh-TW']);
    $assert($r->getStatusCode()===201 && $j['data']['tokenType']==='Bearer','Invited registration '.json_encode($j));
    $registered=User::where('email',$email)->first(); $cleanupUsers[]=$registered;
    $assert($registered->invite_user_id===$user->id && $registered->language==='zh-TW','Registration preserves invitation and language');
    $registrationToken=$j['data']['accessToken'];
    Illuminate\Support\Facades\Cache::put(App\Utils\CacheKey::get('EMAIL_VERIFY_CODE',$email),'123456',300);
    [$r,$j]=$call('POST','/api/v10/auth/password-resets',['email'=>$email,'password'=>'V10changedpassword','emailCode'=>'123456']);
    $assert($r->getStatusCode()===204 && !App\Services\AuthService::decryptAuthData($registrationToken),'Password reset revokes shared sessions');
    [$r,$j]=$call('GET','/api/v10/public/settings',[],null,'en-US;q=0.3, zh-TW;q=0.9');
    $assert($r->headers->get('Content-Language')==='zh-TW','Language quality negotiation');
    Illuminate\Support\Facades\Cache::forget(App\Utils\CacheKey::get('LAST_SEND_EMAIL_VERIFY_TIMESTAMP',$email));
    Illuminate\Support\Facades\RateLimiter::clear('email-invitation:'.$user->id);
    [$r,$j]=$call('PATCH','/api/v10/me',['expiryReminders'=>false,'trafficReminders'=>true],$bearer);
    $assert($r->getStatusCode()===204 && $user->fresh()->remind_expire===0 && $user->fresh()->remind_traffic===1,'Boolean preferences adapt to shared validation');
    $before=$user->fresh()->getAttributes();
    [$r,$j]=$call('GET','/api/v10/me/subscription',[],$bearer);
    $assert($r->getStatusCode()===200 && $before===$user->fresh()->getAttributes(),'Subscription GET does not write business records');
    $imageName=sha1((string)Str::uuid()).'.png';
    Illuminate\Support\Facades\Storage::disk('local')->put('banners/'.$imageName,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5y0AAAAASUVORK5CYII='));
    [$r,$j]=$call('GET','/api/v10/public/banner-images/'.$imageName);
    $assert($r instanceof Symfony\Component\HttpFoundation\BinaryFileResponse && $r->getStatusCode()===200 && str_contains($r->headers->get('Content-Type'),'image/'),'Native image and CORS response');
    Illuminate\Support\Facades\Storage::disk('local')->delete('banners/'.$imageName);
    $app->instance(App\Services\UsageResetService::class,new class extends App\Services\UsageResetService { public function summary(int $userId): array { throw new RuntimeException('/private/path must not leak'); } });
    [$r,$j]=$call('GET','/api/v10/me/usage-resets',[],$bearer);
    $assert($r->getStatusCode()===500 && !str_contains($j['detail'],'private') && !isset($j['trace']),'Internal exceptions are redacted');
    $app->forgetInstance(App\Services\UsageResetService::class);
    [$r,$j]=$call('GET','/api/v10');
    $assert($r->getStatusCode()===404 && $j['code']==='NOT_FOUND','API root also uses problem details');
    [$r,$j]=$call('GET','/api/v10/me/nodes',[],$bearer);
    $etag=$r->headers->get('ETag');
    [$r,$j]=$call('GET','/api/v10/me/nodes',[],$bearer,'en-US',['HTTP_IF_NONE_MATCH'=>$etag]);
    $assert($r->getStatusCode()===304 && $r->getContent()==='' && $r->headers->get('ETag')===$etag,'Conditional resource reads keep native 304');
    $user->banned=1;$user->save();
    [$r,$j]=$call('GET','/api/v10/me',[],$bearer);
    $assert($r->getStatusCode()===403,'Banned authorization');
    $user->banned=0;$user->save();
    [$r,$j]=$call('DELETE','/api/v10/me/session',[],$bearer);
    $assert($r->getStatusCode()===204 && !App\Services\AuthService::decryptAuthData($credentials['auth_data']),'Cross-version revocation');
    echo "V10 contracts: $checks checks passed\n";
} finally { foreach ($cleanupUsers as $fixture) if ($fixture) (new App\Services\AuthService($fixture))->removeAllSession(); DB::rollBack(); }

