<?php
require __DIR__.'/../vendor/autoload.php';
$app = require __DIR__.'/../bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
set_exception_handler(function (Throwable $error) { fwrite(STDERR, $error->getMessage().PHP_EOL); exit(1); });
if (!app()->environment('local')) throw new RuntimeException('Local test only');
use App\Models\User;
use App\Models\Plan;
use App\Models\Order;
use App\Services\TrafficCreditService;
use App\Services\TrafficResetSchedule;
use App\Services\OrderService;
use App\Services\UserService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redis;
use Illuminate\Support\Str;
$checks=0;
$assert=function($ok,$label)use(&$checks){if(!$ok)throw new RuntimeException($label);$checks++;};
$kernel=$app->make(Illuminate\Contracts\Http\Kernel::class);
$index=0;$auths=[];
$call=function($path,$body,$token=null)use($kernel,&$index){
 $r=Illuminate\Http\Request::create('/api/v10/'.$path,$body===null?'GET':'POST',$body??[],[],[],['REMOTE_ADDR'=>'192.0.2.'.(++$index)]);
 $r->headers->set('Accept','application/json');if($token)$r->headers->set('Authorization','Bearer '.$token);
 return $kernel->handle($r);
};
DB::beginTransaction();
try {
 $plan=Plan::create(['name'=>'Credit test','group_id'=>1,'transfer_enable'=>10,'onetime_price'=>1000,'show'=>1,'renew'=>1,'device_limit'=>4,'speed_limit'=>100]);
 $recurring=Plan::create(['name'=>'Recurring test','group_id'=>2,'transfer_enable'=>100,'month_price'=>1000,'show'=>1,'renew'=>1,'reset_traffic_method'=>0]);
 $make=function($fields=[])use($plan){return User::create(array_merge(['email'=>'credit-'.Str::uuid().'@example.com','password'=>'test-only','token'=>Str::random(32),'uuid'=>(string)Str::uuid(),'plan_id'=>$plan->id,'group_id'=>1,'device_limit'=>4,'speed_limit'=>100,'transfer_enable'=>1000,'u'=>200,'d'=>300,'expired_at'=>null],$fields));};
 $user=$make();$service=new TrafficCreditService();$identity=$user->only(['plan_id','group_id','device_limit','speed_limit','expired_at','token','uuid','password']);
 $service->migrateUser($user);$user->save();
 $assert($user->credit_balance===500 && $user->transfer_enable===0,'Legacy unused allowance not preserved');
 $assert($user->only(array_keys($identity))===$identity && $user->u===200,'Migration changed access or history');
 $service->migrateUser($user);$user->save();
 $assert($user->credit_balance===500 && DB::table('v2_traffic_credit_log')->where('reference','legacy:'.$user->id)->count()===1,'Migration duplicated balance');
 $exhausted=$make(['u'=>1200]);$service->migrateUser($exhausted);$exhausted->save();$assert($exhausted->credit_balance===0,'Exhausted user received credits');
 $active=$make(['expired_at'=>time()+86400*90,'u'=>800,'d'=>100,'credit_balance'=>500,'plan_id'=>$recurring->id,'group_id'=>2]);
 $service->migrateUser($active);$assert($active->transfer_enable===1000,'Recurring user migrated');
 $auth=new App\Services\AuthService($active);$auths[]=$auth;$token=$auth->generateAuthData(Illuminate\Http\Request::create('/'))['auth_data'];
 $assert($call('credit-packages',null)->getStatusCode()===401,'Anonymous catalog accepted');
 $catalog=json_decode($call('credit-packages',null,$token)->getContent(),true)['data'];
 $assert(in_array($plan->id,array_column($catalog,'id')),'Credit catalog missing one-time plan');
 $plans=json_decode($call('plans',null,$token)->getContent(),true)['data'];
 $assert(!in_array($plan->id,array_column($plans,'id')) && in_array($recurring->id,array_column($plans,'id')),'One-time plan not separated');
 $r=$call('me/orders',['planId'=>$plan->id,'billingPeriod'=>'credits'],$token);$assert($r->getStatusCode()===201,'Credit order save failed: '.$r->getContent());
 $order=Order::where('trade_no',json_decode($r->getContent(),true)['data']['orderNumber'])->firstOrFail();
 $assert($order->type===5 && $order->credit_bytes===10*1073741824 && !$order->surplus_amount,'Credit order converted subscription');
 $before=$active->fresh()->only(['u','d','transfer_enable','expired_at','plan_id','group_id','device_limit','speed_limit','token']);
 $plan->update(['transfer_enable'=>50]);$order->status=1;$order->save();
 (new OrderService($order))->open();$active->refresh();
 $assert($active->credit_balance===500+10*1073741824,'Purchase used changed plan instead of snapshot');
 $assert($active->only(array_keys($before))===$before,'Credits replaced subscription');
 (new OrderService($order))->open();$assert($active->refresh()->credit_balance===500+10*1073741824,'Retry doubled credits');
 (new OrderService($order))->paid('stale-callback');$assert($order->fresh()->status===3,'Stale payment callback reopened a completed order');
 $active->update(['credit_balance'=>500]);
 $report=function($u,$d)use($active){
  $redis=Redis::getFacadeRoot();
  try {Redis::swap(new class($active->id,$u,$d){private $id,$u,$d;function __construct($id,$u,$d){$this->id=$id;$this->u=$u;$this->d=$d;}function exists($k){return false;}function hgetall($k){return [$this->id=>strpos($k,'upload')!==false?$this->u:$this->d];}function del($k){return 1;}});
  (new App\Console\Commands\TrafficUpdate())->handle();}finally{Redis::swap($redis);}
 };
 $report(20,30);$assert($active->refresh()->credit_balance===500 && $active->u+$active->d===950,'Credits used before base');
 $report(0,100);$assert($active->refresh()->credit_balance===450 && $active->u+$active->d===1050,'Cross-boundary debit wrong');
 $report(25,0);$assert($active->refresh()->credit_balance===425,'Upload-only credits debit wrong');
 $assert(User::withUsableTraffic()->where('id',$active->id)->exists(),'Quota exhausted with credit denied');
 $active->update(['u'=>0,'d'=>0]);$report(10,20);$assert($active->refresh()->credit_balance===425,'Reset refunded or consumed credits');
 $active->update(['expired_at'=>time()-1]);$report(25,25);$assert($active->refresh()->credit_balance===375,'Expired subscription received free base allowance');
 $assert((new UserService())->isAvailable($active) && User::withUsableTraffic()->where('id',$active->id)->exists(),'Standalone credits denied');
 $assert((new App\Services\AccountStatusService())->forUser($active)['state']==='active','Credit user sent to expired page');
 $client=TrafficCreditService::forClient($active);$assert($client->expired_at===null && $client->transfer_enable-$client->u-$client->d===375,'Client remaining or expiry incorrect');
 $active->update(['banned'=>1]);$assert(!(new UserService())->isAvailable($active) && !User::withUsableTraffic()->where('id',$active->id)->exists(),'Banned credit account enabled');
 $active->update(['banned'=>0]);$report(1000,1000);$assert($active->refresh()->credit_balance===0 && !User::withUsableTraffic()->where('id',$active->id)->exists(),'Credit overspend not bounded');
 $fresh=$make(['plan_id'=>null,'group_id'=>null,'transfer_enable'=>0,'u'=>0,'d'=>0,'expired_at'=>0]);
 $buy=Order::create(['user_id'=>$fresh->id,'plan_id'=>$plan->id,'trade_no'=>Str::random(24),'period'=>'onetime_price','type'=>5,'status'=>1,'total_amount'=>1000,'credit_bytes'=>100,'credit_snapshot'=>['name'=>'snapshot','group_id'=>1,'speed_limit'=>100,'device_limit'=>4]]);
 (new OrderService($buy))->open();$fresh->refresh();$assert($fresh->credit_balance===100 && $fresh->group_id===1 && $fresh->transfer_enable===0,'First credit purchase failed independent access');
 $assert((new UserService())->isAvailable($fresh),'New independent account unavailable');
 $assert(!(new UserService())->getUnAvailbaleUsers()->contains('id',$fresh->id),'Independent credits included in unavailable accounts');
 $legacy=$make();$old=Order::create(['user_id'=>$legacy->id,'plan_id'=>$recurring->id,'trade_no'=>Str::random(24),'period'=>'month_price','type'=>3,'status'=>0,'total_amount'=>1,'surplus_amount'=>100]);
 $service->migrateUser($legacy);$assert(!$legacy->credit_migrated_at && !$legacy->credit_balance,'Pending exchange double-counted allowance');
 (new OrderService($old))->cancel();$assert($legacy->refresh()->credit_balance===500 && $legacy->transfer_enable===0,'Cancelled legacy quote not migrated');
 $legacy2=$make();$old2=Order::create(['user_id'=>$legacy2->id,'plan_id'=>$plan->id,'trade_no'=>Str::random(24),'period'=>'onetime_price','type'=>2,'status'=>1,'total_amount'=>1000]);
 (new OrderService($old2))->open();$assert($legacy2->refresh()->credit_balance===50*1073741824+500 && $legacy2->transfer_enable===0,'Legacy pending one-time order lost allowance');
 (new OrderService($old2))->open();$assert($legacy2->refresh()->credit_balance===50*1073741824+500,'Legacy order retried twice');
 $legacyReset=$make();$resetOrder=Order::create(['user_id'=>$legacyReset->id,'plan_id'=>$plan->id,'trade_no'=>Str::random(24),'period'=>'reset_price','type'=>4,'status'=>1,'total_amount'=>100]);
 $service->migrateUser($legacyReset);$assert(!$legacyReset->credit_migrated_at,'Pending old reset migrated too early');
 (new OrderService($resetOrder))->open();$assert($legacyReset->refresh()->credit_balance===1000 && $legacyReset->transfer_enable===0,'Old paid reset lost its promised allowance');
 $legacySwitch=$make();$switchOrder=Order::create(['user_id'=>$legacySwitch->id,'plan_id'=>$recurring->id,'trade_no'=>Str::random(24),'period'=>'month_price','type'=>3,'status'=>1,'total_amount'=>100,'surplus_amount'=>100]);
 $service->migrateUser($legacySwitch);(new OrderService($switchOrder))->open();$assert($legacySwitch->refresh()->credit_balance===0 && $legacySwitch->plan_id===$recurring->id,'Old discounted switch duplicated converted traffic');
 $migration=require __DIR__.'/../database/migrations/2026_10_02_000005_create_traffic_credits.php';$before=$legacy2->credit_balance;$migration->up();$migration->up();$assert($legacy2->refresh()->credit_balance===$before,'Migration rerun changed balance');
 $assert(App\Services\AuthService::decryptAuthData($token)!==false,'Migration invalidated login');
 $assert((new App\Services\ServerService())->getAvailableUsers([1])->contains('id',$fresh->id),'Independent credit account missing from node authentication');
 $assert(!(new App\Services\ServerService())->getAvailableUsers([2])->contains('id',$fresh->id),'Credit account leaked into another node group');
 $assert((new UserService())->getDeviceLimitedUsers()->contains('id',$fresh->id),'Independent account bypassed device checks');
 $info=json_decode($call('me/subscription',null,$token)->getContent(),true)['data'];$assert(array_key_exists('resetAt',$info) && array_key_exists('creditBytes',$info),'API metadata missing');
 $assert(TrafficResetSchedule::next(0,strtotime('2027-01-01'),strtotime('2026-10-02 13:45'))===strtotime('2026-11-01 00:00'),'Month-first reset timestamp wrong');
 $assert(TrafficResetSchedule::next(1,strtotime('2027-03-31 12:00'),strtotime('2026-01-31 13:00'))===strtotime('2026-02-28 00:00'),'Month-end clamping wrong');
 $assert(TrafficResetSchedule::next(1,strtotime('2026-10-25 12:00'),strtotime('2026-10-02'))===null,'25-day guard not respected');
 $assert(TrafficResetSchedule::next(3,strtotime('2028-01-01'),strtotime('2026-10-02'))===strtotime('2027-01-01'),'Year-first reset wrong');
 $assert(TrafficResetSchedule::next(4,strtotime('2032-02-29'),strtotime('2026-10-02'))===strtotime('2028-02-29'),'Leap-year reset wrong');
 $assert(TrafficResetSchedule::next(2,strtotime('2028-01-01'))===null && TrafficResetSchedule::next(0,null)===null,'No reset plan reported timestamp');
 echo "Traffic credits: $checks checks passed\n";
} finally {foreach($auths as $auth)$auth->removeAllSession(); DB::rollBack();}
