import i18n from "./i18n";

const copy = {
    notificationAutoSave: ["更改会自动保存", "變更會自動儲存", "Changes save automatically", "変更は自動保存されます", "변경 사항이 자동으로 저장됩니다", "Thay đổi được lưu tự động", "Изменения сохраняются автоматически", "تغییرات خودکار ذخیره می‌شوند"],
    notificationSaving: ["正在保存…", "正在儲存…", "Saving…", "保存中…", "저장 중…", "Đang lưu…", "Сохранение…", "در حال ذخیره…"],
    notificationFailed: ["保存失败，已恢复原设置。请重新切换以重试。", "儲存失敗，已還原原設定。請重新切換以重試。", "Could not save. Your previous setting was restored. Toggle again to retry.", "保存できませんでした。元の設定に戻しました。もう一度切り替えてください。", "저장하지 못해 이전 설정으로 복원했습니다. 다시 전환해 주세요.", "Không thể lưu. Đã khôi phục cài đặt trước. Bật/tắt lại để thử lại.", "Не удалось сохранить. Прежняя настройка восстановлена. Переключите снова.", "ذخیره نشد. تنظیم قبلی بازگردانده شد. برای تلاش دوباره کلید را تغییر دهید."],
    expiryHelp: ["服务即将到期时，通过邮件提醒。", "服務即將到期時，透過郵件提醒。", "Receive an email when your service is nearing expiry.", "サービスの有効期限が近づいたらメールでお知らせします。", "서비스 만료가 가까워지면 이메일로 알려드립니다.", "Nhận email khi dịch vụ sắp hết hạn.", "Получайте письмо перед окончанием срока услуги.", "نزدیک پایان اعتبار سرویس، ایمیل یادآوری دریافت کنید."],
    giftIntro: [
        "一份心意，即刻使用",
        "一份心意，即刻使用",
        "A gift, ready to use",
        "贈りものを、今すぐ",
        "선물을 바로 사용하세요",
        "Món quà sẵn sàng để dùng",
        "Подарок, готовый к использованию",
        "هدیه‌ای آمادهٔ استفاده",
    ],
    giftDetail: [
        "输入礼品卡代码，将对应权益兑换至当前账户。",
        "輸入禮品卡代碼，將對應權益兌換至目前帳戶。",
        "Enter your gift card code to apply its benefits to this account.",
        "コードを入力して、このアカウントで特典を受け取ります。",
        "기프트 카드 코드를 입력하면 현재 계정에 혜택이 적용됩니다.",
        "Nhập mã thẻ quà tặng để áp dụng quyền lợi cho tài khoản này.",
        "Введите код подарочной карты, чтобы применить её к этому аккаунту.",
        "کد کارت هدیه را وارد کنید تا مزایای آن به این حساب اعمال شود.",
    ],
    redeemAccount: [
        "兑换到账户",
        "兌換至帳戶",
        "Redeem to account",
        "受け取りアカウント",
        "혜택을 받을 계정",
        "Đổi cho tài khoản",
        "Аккаунт получателя",
        "حساب دریافت‌کننده",
    ],
    giftHint: [
        "请确认账户无误。兑换内容及使用条件以礼品卡规则为准。",
        "請確認帳戶無誤。兌換內容及使用條件以禮品卡規則為準。",
        "Check your account before redeeming. Benefits and eligibility depend on the card.",
        "アカウントをご確認ください。特典と利用条件はカードによって異なります。",
        "계정을 확인해 주세요. 혜택과 사용 조건은 카드에 따라 다릅니다.",
        "Kiểm tra tài khoản trước khi đổi. Quyền lợi và điều kiện tùy theo thẻ.",
        "Проверьте аккаунт. Содержимое и условия использования зависят от карты.",
        "حساب را بررسی کنید. مزایا و شرایط استفاده به کارت بستگی دارد.",
    ],
    giftDone: [
        "礼品卡权益已到账。可在账单与使用情况中查看更新后的信息。",
        "禮品卡權益已到帳。可在帳單與使用情況中查看更新後的資訊。",
        "Your gift has been applied. Check billing and usage for your updated details.",
        "特典が適用されました。請求と利用状況で更新内容をご確認ください。",
        "혜택이 적용되었습니다. 청구 및 사용 현황에서 변경 내용을 확인하세요.",
        "Quyền lợi đã được áp dụng. Xem thông tin mới trong hóa đơn và mức sử dụng.",
        "Подарок применён. Обновлённые сведения доступны в оплате и использовании.",
        "مزایای هدیه اعمال شد. اطلاعات به‌روز را در صورتحساب و مصرف ببینید.",
    ],
    serviceNotice: [
        "开通与续期通知",
        "開通與續期通知",
        "Activation and renewal",
        "開通・更新の通知",
        "개통 및 갱신 알림",
        "Thông báo kích hoạt và gia hạn",
        "Активация и продление",
        "اعلان فعال‌سازی و تمدید",
    ],
    quotaNotice: [
        "额度提醒",
        "額度提醒",
        "Allowance reminders",
        "利用枠の通知",
        "사용량 한도 알림",
        "Nhắc hạn mức",
        "Напоминания о лимите",
        "یادآوری سهمیه",
    ],
    notificationIntro: [
        "选择希望通过邮件接收的服务通知。",
        "選擇希望透過郵件接收的服務通知。",
        "Choose the service updates you receive by email.",
        "メールで受け取るサービス通知を選択します。",
        "이메일로 받을 서비스 알림을 선택하세요.",
        "Chọn thông báo dịch vụ muốn nhận qua email.",
        "Выберите уведомления о сервисе по электронной почте.",
        "اعلان‌های خدماتی موردنظر برای دریافت با ایمیل را انتخاب کنید.",
    ],
    serviceHelp: [
        "服务实际开通或续期成功后通知。",
        "服務實際開通或續期成功後通知。",
        "After your service has been activated or renewed successfully.",
        "サービスの開通または更新が完了したとき。",
        "서비스 개통 또는 갱신이 완료되면 알립니다.",
        "Khi dịch vụ được kích hoạt hoặc gia hạn thành công.",
        "После успешной активации или продления сервиса.",
        "پس از فعال‌سازی یا تمدید موفق سرویس.",
    ],
    quotaHelp: [
        "套餐额度使用超过 95% 时提醒。",
        "套餐額度使用超過 95% 時提醒。",
        "When more than 95% of your plan allowance is used.",
        "プランの利用枠を95%以上使用したとき。",
        "요금제 한도의 95% 이상을 사용하면 알립니다.",
        "Khi đã dùng hơn 95% hạn mức gói.",
        "Когда использовано более 95% лимита плана.",
        "وقتی بیش از ۹۵٪ سهمیهٔ طرح مصرف شده باشد.",
    ],
} as const;
const languages = [
    "zh-CN",
    "zh-TW",
    "en-US",
    "ja-JP",
    "ko-KR",
    "vi-VN",
    "ru-RU",
    "fa-IR",
];
languages.forEach((locale, index) =>
    i18n.addResourceBundle(
        locale,
        "account",
        Object.fromEntries(
            Object.entries(copy).map(([key, values]) => [key, values[index]]),
        ),
    ),
);
export const ac = (key: keyof typeof copy): string =>
    String(i18n.t(key, { ns: "account" }));
