import i18n from "../shared/i18n";
export const announcementCopy = {
    title: [
        "公告",
        "公告",
        "Announcements",
        "お知らせ",
        "공지",
        "Thông báo",
        "Объявления",
        "اطلاعیه‌ها",
    ],
    intro: [
        "产品更新与服务消息",
        "產品更新與服務消息",
        "Product updates and service news",
        "製品の更新とサービス情報",
        "제품 업데이트 및 서비스 소식",
        "Cập nhật sản phẩm và tin dịch vụ",
        "Обновления продукта и новости сервиса",
        "به‌روزرسانی محصول و اخبار سرویس",
    ],
    unreadLabel: [
        "公告，{{count}} 条未读",
        "公告，{{count}} 則未讀",
        "Announcements, {{count}} unread",
        "お知らせ、未読 {{count}} 件",
        "공지, 읽지 않음 {{count}}개",
        "Thông báo, {{count}} chưa đọc",
        "Объявления: {{count}} непрочитанных",
        "اطلاعیه‌ها، {{count}} خوانده‌نشده",
    ],
    unreadCount: [
        "{{count}} 条未读",
        "{{count}} 則未讀",
        "{{count}} unread",
        "未読 {{count}} 件",
        "읽지 않음 {{count}}개",
        "{{count}} chưa đọc",
        "Не прочитано: {{count}}",
        "{{count}} خوانده‌نشده",
    ],
    unread: [
        "未读",
        "未讀",
        "Unread",
        "未読",
        "읽지 않음",
        "Chưa đọc",
        "Не прочитано",
        "خوانده‌نشده",
    ],
    empty: [
        "暂无公告",
        "暫無公告",
        "No announcements yet",
        "お知らせはありません",
        "아직 공지가 없습니다",
        "Chưa có thông báo",
        "Объявлений пока нет",
        "هنوز اطلاعیه‌ای نیست",
    ],
    emptyHint: [
        "新的产品与服务消息会显示在这里。",
        "新的產品與服務消息會顯示在這裡。",
        "New product and service updates will appear here.",
        "新しい製品やサービスの情報がここに表示されます。",
        "새로운 제품 및 서비스 소식이 여기에 표시됩니다.",
        "Tin mới về sản phẩm và dịch vụ sẽ xuất hiện ở đây.",
        "Здесь появятся новости продукта и сервиса.",
        "اخبار جدید محصول و سرویس اینجا نمایش داده می‌شوند.",
    ],
    back: [
        "全部公告",
        "全部公告",
        "All announcements",
        "すべてのお知らせ",
        "모든 공지",
        "Tất cả thông báo",
        "Все объявления",
        "همه اطلاعیه‌ها",
    ],
    previous: [
        "上一页公告",
        "上一頁公告",
        "Previous announcements",
        "前のページ",
        "이전 공지",
        "Thông báo trước",
        "Предыдущие объявления",
        "اطلاعیه‌های قبلی",
    ],
    next: [
        "下一页公告",
        "下一頁公告",
        "Next announcements",
        "次のページ",
        "다음 공지",
        "Thông báo tiếp theo",
        "Следующие объявления",
        "اطلاعیه‌های بعدی",
    ],
    loadError: [
        "公告暂时无法加载，请重试。",
        "公告暫時無法載入，請重試。",
        "Announcements couldn't load. Please try again.",
        "お知らせを読み込めません。再試行してください。",
        "공지를 불러오지 못했습니다. 다시 시도하세요.",
        "Không tải được thông báo. Vui lòng thử lại.",
        "Не удалось загрузить объявления. Повторите попытку.",
        "اطلاعیه‌ها بارگیری نشدند. دوباره تلاش کنید.",
    ],
    unavailable: [
        "这条公告暂时不可用，可能已被撤下。",
        "這則公告暫時不可用，可能已被撤下。",
        "This announcement is unavailable. It may have been withdrawn.",
        "このお知らせは利用できません。公開が終了した可能性があります。",
        "이 공지는 사용할 수 없습니다. 게시가 중단되었을 수 있습니다.",
        "Thông báo này không khả dụng, có thể đã bị gỡ.",
        "Объявление недоступно. Возможно, оно снято с публикации.",
        "این اطلاعیه در دسترس نیست و ممکن است حذف شده باشد.",
    ],
    readError: [
        "已读状态未能保存，请重试。",
        "已讀狀態未能儲存，請重試。",
        "Couldn't save your read status. Please try again.",
        "既読状態を保存できませんでした。再試行してください。",
        "읽음 상태를 저장하지 못했습니다. 다시 시도하세요.",
        "Không lưu được trạng thái đã đọc. Vui lòng thử lại.",
        "Не удалось сохранить отметку о прочтении. Повторите попытку.",
        "وضعیت خواندن ذخیره نشد. دوباره تلاش کنید.",
    ],
    changed: [
        "公告已更新，请重新加载后阅读。",
        "公告已更新，請重新載入後閱讀。",
        "This announcement has changed. Reload to read the update.",
        "お知らせが更新されました。再読み込みしてください。",
        "공지가 업데이트되었습니다. 새로고침하여 확인하세요.",
        "Thông báo đã thay đổi. Hãy tải lại để đọc bản cập nhật.",
        "Объявление изменилось. Загрузите его заново.",
        "این اطلاعیه تغییر کرده است. برای خواندن نسخه جدید دوباره بارگیری کنید.",
    ],
};
[
    "zh-CN",
    "zh-TW",
    "en-US",
    "ja-JP",
    "ko-KR",
    "vi-VN",
    "ru-RU",
    "fa-IR",
].forEach((code, index) =>
    i18n.addResourceBundle(
        code,
        "announcements",
        Object.fromEntries(
            Object.entries(announcementCopy).map(([key, values]) => [
                key,
                values[index],
            ]),
        ),
    ),
);
export const a = (
    key: keyof typeof announcementCopy,
    values?: Record<string, unknown>,
): string => String(i18n.t(key, { ns: "announcements", ...values }));
