<?php
return [
    'zh-CN'=>[
        'metadata_aliases'=>['剩余流量','套餐到期','计划重置'],
        'no_plan'=>'暂无可用套餐或额度',
        'expired'=>'套餐已到期，请续费或购买额度',
        'user_unavailable'=>'订阅暂不可用，请查看账户状态',
        'banned'=>'账户已停用，请联系支持',
        'client_disabled'=>'此客户端暂不支持，请更换客户端',
        'client_version_too_low'=>'客户端版本过旧，请更新后重新导入',
        'remaining'=>'剩余',
        'expiry'=>'到期',
        'reset'=>'重置',
        'unlimited'=>'长期有效',
    ],
    'zh-TW'=>[
        'metadata_aliases'=>['剩餘流量','方案到期','預定重置'],
        'no_plan'=>'暫無可用方案或額度',
        'expired'=>'方案已到期，請續費或購買額度',
        'user_unavailable'=>'訂閱暫不可用，請查看帳戶狀態',
        'banned'=>'帳戶已停用，請聯絡支援',
        'client_disabled'=>'此用戶端暫不支援，請更換用戶端',
        'client_version_too_low'=>'用戶端版本過舊，請更新後重新匯入',
        'remaining'=>'剩餘',
        'expiry'=>'到期',
        'reset'=>'重置',
        'unlimited'=>'長期有效',
    ],
    'en-US'=>[
        'metadata_aliases'=>['Remaining data','Plan expires','Scheduled reset'],
        'no_plan'=>'No available plan or credits',
        'expired'=>'Plan expired; renew or buy credits',
        'user_unavailable'=>'Subscription unavailable; check your account',
        'banned'=>'Account disabled; contact support',
        'client_disabled'=>'Client unsupported; choose another client',
        'client_version_too_low'=>'Update your client, then import again',
        'remaining'=>'Remaining',
        'expiry'=>'Expires',
        'reset'=>'Reset',
        'unlimited'=>'No expiry',
    ],
    'ja-JP'=>[
        'metadata_aliases'=>['残りの容量','プラン有効期限','次回リセット'],
        'no_plan'=>'利用可能なプランまたは容量がありません',
        'expired'=>'期限切れです。更新または容量を購入してください',
        'user_unavailable'=>'利用できません。アカウント状態を確認してください',
        'banned'=>'アカウント停止中です。サポートにお問い合わせください',
        'client_disabled'=>'別の対応クライアントを選んでください',
        'client_version_too_low'=>'クライアントを更新してから再度インポートしてください',
        'remaining'=>'残量',
        'expiry'=>'期限',
        'reset'=>'リセット',
        'unlimited'=>'有効期限なし',
    ],
    'ko-KR'=>[
        'metadata_aliases'=>['남은 데이터','요금제 만료','예정된 초기화'],
        'no_plan'=>'사용 가능한 요금제 또는 용량이 없습니다',
        'expired'=>'요금제가 만료되었습니다. 갱신하거나 용량을 구매하세요',
        'user_unavailable'=>'구독을 사용할 수 없습니다. 계정 상태를 확인하세요',
        'banned'=>'계정이 비활성화되었습니다. 지원팀에 문의하세요',
        'client_disabled'=>'지원되지 않는 클라이언트입니다. 다른 앱을 선택하세요',
        'client_version_too_low'=>'클라이언트를 업데이트한 후 다시 가져오세요',
        'remaining'=>'잔여',
        'expiry'=>'만료',
        'reset'=>'초기화',
        'unlimited'=>'만료 없음',
    ],
    'vi-VN'=>[
        'metadata_aliases'=>['Dung lượng còn lại','Gói hết hạn','Đặt lại theo lịch'],
        'no_plan'=>'Không có gói hoặc dung lượng khả dụng',
        'expired'=>'Gói đã hết hạn; hãy gia hạn hoặc mua dung lượng',
        'user_unavailable'=>'Đăng ký chưa khả dụng; kiểm tra tài khoản',
        'banned'=>'Tài khoản bị vô hiệu hóa; liên hệ hỗ trợ',
        'client_disabled'=>'Ứng dụng chưa được hỗ trợ; chọn ứng dụng khác',
        'client_version_too_low'=>'Cập nhật ứng dụng rồi nhập lại cấu hình',
        'remaining'=>'Còn lại',
        'expiry'=>'Hết hạn',
        'reset'=>'Đặt lại',
        'unlimited'=>'Không hết hạn',
    ],
    'ru-RU'=>[
        'metadata_aliases'=>['Остаток трафика','Срок тарифа','Плановый сброс'],
        'no_plan'=>'Нет доступного тарифа или объёма',
        'expired'=>'Тариф истёк: продлите или купите объём',
        'user_unavailable'=>'Подписка недоступна: проверьте состояние аккаунта',
        'banned'=>'Аккаунт отключён: обратитесь в поддержку',
        'client_disabled'=>'Клиент не поддерживается: выберите другой',
        'client_version_too_low'=>'Обновите клиент и импортируйте снова',
        'remaining'=>'Остаток',
        'expiry'=>'До',
        'reset'=>'Сброс',
        'unlimited'=>'Бессрочно',
    ],
    'fa-IR'=>[
        'metadata_aliases'=>['ترافیک باقی‌مانده','انقضای طرح','بازنشانی زمان‌بندی‌شده'],
        'no_plan'=>'طرح یا اعتبار قابل استفاده‌ای وجود ندارد',
        'expired'=>'طرح منقضی شده؛ تمدید کنید یا اعتبار بخرید',
        'user_unavailable'=>'اشتراک در دسترس نیست؛ وضعیت حساب را بررسی کنید',
        'banned'=>'حساب غیرفعال است؛ با پشتیبانی تماس بگیرید',
        'client_disabled'=>'این برنامه پشتیبانی نمی‌شود؛ برنامه دیگری انتخاب کنید',
        'client_version_too_low'=>'برنامه را به‌روزرسانی کنید و دوباره وارد کنید',
        'remaining'=>'باقی‌مانده',
        'expiry'=>'انقضا',
        'reset'=>'بازنشانی',
        'unlimited'=>'بدون انقضا',
    ],
];
