import i18n from "./i18n";
export const billingCopy = {
    usageDetails: [
        "使用明细",
        "使用明細",
        "Usage details",
        "利用明細",
        "사용 내역",
        "Chi tiết sử dụng",
        "Подробности расхода",
        "جزئیات مصرف",
    ],
    billingIntro: [
        "管理订阅、账户余额与付款记录。",
        "管理訂閱、帳戶餘額與付款記錄。",
        "Manage your subscription, balance and payments.",
        "契約、残高、お支払いを管理します。",
        "구독, 잔액 및 결제 내역을 관리하세요.",
        "Quản lý gói, số dư và thanh toán.",
        "Управляйте подпиской, балансом и платежами.",
        "اشتراک، موجودی و پرداخت‌ها را مدیریت کنید.",
    ],
    currentPlan: [
        "当前订阅",
        "目前訂閱",
        "Current subscription",
        "現在の契約",
        "현재 구독",
        "Gói hiện tại",
        "Текущая подписка",
        "اشتراک فعلی",
    ],
    choosePlan: [
        "选择适合你的套餐，随时开始。",
        "選擇適合你的方案，隨時開始。",
        "Choose a plan to get started.",
        "プランを選んで始めましょう。",
        "요금제를 선택하고 시작하세요.",
        "Chọn gói để bắt đầu.",
        "Выберите тариф, чтобы начать.",
        "برای شروع یک طرح انتخاب کنید.",
    ],
    balanceHelp: [
        "余额可用于抵扣订阅订单，实际抵扣金额会在付款前显示。",
        "餘額可用於折抵訂閱訂單，實際折抵金額會在付款前顯示。",
        "Your balance can cover subscription orders. Applied amounts appear before payment.",
        "残高は契約のお支払いに使えます。適用額は支払い前に表示されます。",
        "잔액으로 구독 주문을 결제할 수 있습니다. 적용 금액은 결제 전에 표시됩니다.",
        "Số dư có thể thanh toán gói. Số tiền áp dụng hiển thị trước khi trả tiền.",
        "Баланс можно использовать для оплаты подписки. Сумма списания видна до оплаты.",
        "موجودی برای پرداخت اشتراک قابل استفاده است. مبلغ کسرشده پیش از پرداخت نمایش داده می‌شود.",
    ],
    transactions: [
        "交易记录",
        "交易記錄",
        "Transactions",
        "取引履歴",
        "거래 내역",
        "Giao dịch",
        "Транзакции",
        "تراکنش‌ها",
    ],
    showLess: [
        "收起",
        "收起",
        "Show less",
        "折りたたむ",
        "접기",
        "Thu gọn",
        "Свернуть",
        "نمایش کمتر",
    ],
    viewAll: [
        "查看全部",
        "查看全部",
        "View all",
        "すべて表示",
        "전체 보기",
        "Xem tất cả",
        "Показать все",
        "نمایش همه",
    ],
    noTransactions: [
        "暂无交易记录",
        "尚無交易記錄",
        "No transactions yet",
        "取引履歴はありません",
        "거래 내역이 없습니다",
        "Chưa có giao dịch",
        "Транзакций пока нет",
        "هنوز تراکنشی ندارید",
    ],
    usageIntro: [
        "查看套餐用量，在需要时恢复可用额度。",
        "查看方案用量，在需要時恢復可用額度。",
        "Track usage and restore your allowance when needed.",
        "利用状況を確認し、必要に応じて利用枠を回復できます。",
        "사용량을 확인하고 필요할 때 한도를 복원하세요.",
        "Theo dõi mức sử dụng và khôi phục hạn mức khi cần.",
        "Следите за расходом и восстанавливайте лимит при необходимости.",
        "مصرف را بررسی و در صورت نیاز سهمیه را بازیابی کنید.",
    ],
    overview: [
        "概览",
        "概覽",
        "Overview",
        "概要",
        "개요",
        "Tổng quan",
        "Обзор",
        "نمای کلی",
    ],
    analysis: [
        "分析",
        "分析",
        "Analytics",
        "分析",
        "분석",
        "Phân tích",
        "Аналитика",
        "تحلیل",
    ],
    usageReset: [
        "使用限额重置",
        "使用限額重置",
        "Usage resets",
        "利用枠のリセット",
        "사용 한도 초기화",
        "Đặt lại hạn mức",
        "Сброс лимита",
        "بازنشانی سهمیه",
    ],
    resetHelp: [
        "使用一次储备重置，清零当前已用流量。套餐额度、到期时间及原定重置日期不变。",
        "使用一次儲備重置，清零目前已用流量。方案額度、到期時間及原定重置日期不變。",
        "Use one banked reset to clear current usage. Your allowance, subscription expiry and scheduled reset date stay the same.",
        "リセットを1回使うと現在の使用量がゼロになります。利用枠、契約期限、定期リセット日は変わりません。",
        "저장된 초기화 1회를 사용하면 현재 사용량이 지워집니다. 한도, 구독 만료일 및 정기 초기화 날짜는 유지됩니다.",
        "Dùng một lượt dự trữ để xóa mức sử dụng hiện tại. Hạn mức, ngày hết hạn và lịch đặt lại không đổi.",
        "Один накопленный сброс обнуляет текущий расход. Лимит, срок подписки и дата планового сброса не меняются.",
        "با یک بازنشانی ذخیره‌شده، مصرف فعلی صفر می‌شود. سهمیه، پایان اشتراک و تاریخ بازنشانی دوره‌ای تغییر نمی‌کنند.",
    ],
    banked: [
        "储备重置 · Banked",
        "儲備重置 · Banked",
        "Banked resets",
        "ストック済みリセット",
        "저장된 초기화",
        "Lượt đặt lại dự trữ",
        "Накопленные сбросы",
        "بازنشانی‌های ذخیره‌شده",
    ],
    available: [
        "次可用",
        "次可用",
        "available",
        "回利用可能",
        "회 사용 가능",
        "lượt khả dụng",
        "доступно",
        "قابل استفاده",
    ],
    resetNow: [
        "提前重置",
        "提前重置",
        "Reset usage",
        "今すぐリセット",
        "지금 초기화",
        "Đặt lại ngay",
        "Сбросить расход",
        "بازنشانی مصرف",
    ],
    bankedHelp: [
        "由管理员发放，可累积。优先使用即将到期的次数。",
        "由管理員發放，可累積。優先使用即將到期的次數。",
        "Granted by your administrator and stored for later. Expiring resets are used first.",
        "管理者から付与され、保存できます。有効期限の近いものから使います。",
        "관리자가 지급하며 누적됩니다. 만료가 가까운 횟수부터 사용됩니다.",
        "Do quản trị viên cấp và có thể tích lũy. Dùng lượt sắp hết hạn trước.",
        "Выдаются администратором и накапливаются. Сначала используются ближайшие к истечению.",
        "مدیر آن‌ها را تخصیص می‌دهد و قابل ذخیره هستند. موارد نزدیک به انقضا زودتر مصرف می‌شوند.",
    ],
    creditCount: [
        "{{count}} 次重置",
        "{{count}} 次重置",
        "{{count}} resets",
        "{{count}} 回のリセット",
        "초기화 {{count}}회",
        "{{count}} lượt đặt lại",
        "Сбросов: {{count}}",
        "{{count}} بازنشانی",
    ],
    expires: [
        "{{date}} 到期",
        "{{date}} 到期",
        "Expires {{date}}",
        "有効期限：{{date}}",
        "만료: {{date}}",
        "Hết hạn {{date}}",
        "Истекает {{date}}",
        "انقضا: {{date}}",
    ],
    resetHistory: [
        "重置记录",
        "重置記錄",
        "Reset history",
        "リセット履歴",
        "초기화 기록",
        "Lịch sử đặt lại",
        "История сбросов",
        "تاریخچه بازنشانی",
    ],
    recentHistory: [
        "近30天 · 最多100条",
        "近30天 · 最多100筆",
        "Last 30 days · up to 100 entries",
        "過去30日・最大100件",
        "최근 30일 · 최대 100건",
        "30 ngày qua · tối đa 100 mục",
        "За 30 дней · до 100 записей",
        "۳۰ روز گذشته · حداکثر ۱۰۰ مورد",
    ],
    granted: [
        "获得储备次数",
        "獲得儲備次數",
        "Banked resets received",
        "リセットを受け取りました",
        "저장 횟수 지급",
        "Đã nhận lượt dự trữ",
        "Получены накопленные сбросы",
        "بازنشانی ذخیره‌شده دریافت شد",
    ],
    consumed: [
        "使用储备重置",
        "使用儲備重置",
        "Banked reset used",
        "ストックを使用",
        "저장된 초기화 사용",
        "Đã dùng lượt dự trữ",
        "Использован накопленный сброс",
        "بازنشانی ذخیره‌شده مصرف شد",
    ],
    globalReset: [
        "管理员全局重置",
        "管理員全域重置",
        "Global reset by administrator",
        "管理者による全体リセット",
        "관리자 전체 초기화",
        "Quản trị viên đặt lại toàn bộ",
        "Глобальный сброс администратором",
        "بازنشانی سراسری توسط مدیر",
    ],
    usageCleared: [
        "已清零 {{amount}} 用量",
        "已清零 {{amount}} 用量",
        "Cleared {{amount}} of usage",
        "{{amount}} の使用量をリセット",
        "사용량 {{amount}} 초기화",
        "Đã xóa {{amount}} sử dụng",
        "Обнулено {{amount}} расхода",
        "{{amount}} مصرف پاک شد",
    ],
    noResetHistory: [
        "近30天暂无重置记录",
        "近30天尚無重置記錄",
        "No resets in the last 30 days",
        "過去30日の履歴はありません",
        "최근 30일 기록이 없습니다",
        "Không có lịch sử trong 30 ngày qua",
        "Нет сбросов за последние 30 дней",
        "در ۳۰ روز گذشته بازنشانی نداشته‌اید",
    ],
    resetConfirm: [
        "将使用 1 次储备重置，清零当前 {{amount}} 已用流量。此操作无法撤销。",
        "將使用 1 次儲備重置，清零目前 {{amount}} 已用流量。此操作無法復原。",
        "Use 1 banked reset to clear {{amount}} of current usage. This cannot be undone.",
        "1回分を使って現在の使用量 {{amount}} をリセットします。取り消せません。",
        "저장된 초기화 1회로 현재 사용량 {{amount}}을 지웁니다. 취소할 수 없습니다.",
        "Dùng 1 lượt dự trữ để xóa {{amount}} đã dùng. Không thể hoàn tác.",
        "Потратить 1 сброс и обнулить текущий расход {{amount}}. Отменить действие нельзя.",
        "یک بازنشانی ذخیره‌شده برای پاک کردن {{amount}} مصرف فعلی استفاده می‌شود. این کار قابل بازگشت نیست.",
    ],
    useOne: [
        "使用 1 次重置",
        "使用 1 次重置",
        "Use 1 reset",
        "1回使う",
        "초기화 1회 사용",
        "Dùng 1 lượt",
        "Использовать 1 сброс",
        "استفاده از ۱ بازنشانی",
    ],
    resetSuccess: [
        "用量已重置，套餐额度已恢复。",
        "用量已重置，方案額度已恢復。",
        "Usage reset. Your allowance is restored.",
        "使用量をリセットし、利用枠を回復しました。",
        "사용량이 초기화되고 한도가 복원되었습니다.",
        "Đã đặt lại và khôi phục hạn mức.",
        "Расход обнулён, лимит восстановлен.",
        "مصرف بازنشانی و سهمیه بازیابی شد.",
    ],
    inactive: [
        "有效套餐用户可使用储备重置。",
        "有效方案使用者可使用儲備重置。",
        "An active subscription is required to use a reset.",
        "有効な契約が必要です。",
        "활성 구독이 필요합니다.",
        "Cần gói còn hiệu lực để dùng.",
        "Для сброса нужна действующая подписка.",
        "برای استفاده، اشتراک فعال لازم است.",
    ],
    emptyUsage: [
        "当前没有需要重置的用量，不会扣除次数。",
        "目前沒有需要重置的用量，不會扣除次數。",
        "There is no usage to reset. No reset will be spent.",
        "リセット対象の使用量はありません。回数は消費されません。",
        "초기화할 사용량이 없어 횟수를 차감하지 않습니다.",
        "Chưa có sử dụng cần đặt lại. Không trừ lượt.",
        "Нет расхода для сброса. Сброс не будет потрачен.",
        "مصرفی برای بازنشانی وجود ندارد و چیزی کسر نمی‌شود.",
    ],
    noCredits: [
        "暂无可用储备次数。管理员发放后会在这里显示。",
        "尚無可用儲備次數。管理員發放後會在這裡顯示。",
        "No banked resets available. Administrator grants will appear here.",
        "利用可能な回数はありません。管理者が付与するとここに表示されます。",
        "사용 가능한 횟수가 없습니다. 관리자 지급 후 표시됩니다.",
        "Chưa có lượt dự trữ. Lượt được cấp sẽ hiện ở đây.",
        "Нет доступных сбросов. Выданные администратором появятся здесь.",
        "بازنشانی ذخیره‌شده ندارید. موارد تخصیص‌یافته توسط مدیر اینجا نمایش داده می‌شوند.",
    ],
};
[
    "zh-CN",
    "zh-TW",
    "en-US",
    "ja-JP",
    "ko-KR",
    "vi-VN",
    "ru-RU",
    "fa-IR",
].forEach((code, index) =>
    i18n.addResourceBundle(
        code,
        "billing",
        Object.fromEntries(
            Object.entries(billingCopy).map(([key, values]) => [
                key,
                values[index],
            ]),
        ),
    ),
);
export const b = (
    key: keyof typeof billingCopy,
    values?: Record<string, unknown>,
): string => String(i18n.t(key, { ns: "billing", ...values }));
