import i18n, { locale } from "./i18n";
export const creditCopy = {
    completedHelp: [
        "订单已处理，可在使用情况中查看当前服务状态。",
        "訂單已處理，可在使用情況中查看目前服務狀態。",
        "Order processed. Check Usage for your current service status.",
        "注文は処理済みです。現在のサービス状態は利用状況で確認できます。",
        "주문이 처리되었습니다. 현재 서비스 상태는 사용 현황에서 확인하세요.",
        "Đơn đã được xử lý. Xem trạng thái dịch vụ hiện tại trong mục sử dụng.",
        "Заказ обработан. Текущий статус услуги — в разделе использования.",
        "سفارش پردازش شد. وضعیت فعلی سرویس را در بخش مصرف ببینید.",
    ],
    credits: [
        "额度",
        "額度",
        "Credits",
        "クレジット",
        "크레딧",
        "Hạn mức",
        "Кредиты",
        "اعتبار",
    ],
    remaining: [
        "剩余额度",
        "剩餘額度",
        "Remaining credits",
        "残りのクレジット",
        "남은 크레딧",
        "Hạn mức còn lại",
        "Остаток кредитов",
        "اعتبار باقی‌مانده",
    ],
    buy: [
        "购买额度",
        "購買額度",
        "Buy credits",
        "クレジットを購入",
        "크레딧 구매",
        "Mua hạn mức",
        "Купить кредиты",
        "خرید اعتبار",
    ],
    help: [
        "套餐流量用完后自动使用，也可独立使用。额度以 GB 计量，不随套餐重置清零。",
        "方案流量用完後自動使用，也可獨立使用。額度以 GB 計量，不隨方案重設歸零。",
        "Used automatically after your plan allowance, or independently. Measured in GB and unaffected by plan resets.",
        "プラン容量の消費後に自動使用。単独でも利用でき、GB 単位の残高はプランのリセットで失効しません。",
        "요금제 용량 소진 후 자동 사용되며 단독 사용도 가능합니다. GB 단위이며 요금제 초기화로 소멸되지 않습니다.",
        "Tự động dùng khi hết dung lượng gói hoặc dùng độc lập. Tính theo GB, không bị xóa khi đặt lại gói.",
        "Используются после лимита тарифа или самостоятельно. Измеряются в ГБ и сохраняются при сбросе тарифа.",
        "پس از اتمام سهمیه طرح یا به‌صورت مستقل مصرف می‌شود. برحسب GB است و با بازنشانی طرح پاک نمی‌شود.",
    ],
    quantity: [
        "选择额度",
        "選擇額度",
        "Choose an amount",
        "容量を選択",
        "용량 선택",
        "Chọn dung lượng",
        "Выберите объём",
        "انتخاب مقدار",
    ],
    empty: [
        "暂无可购买额度",
        "暫無可購買額度",
        "No credits available to purchase",
        "購入できるクレジットはありません",
        "구매 가능한 크레딧이 없습니다",
        "Chưa có hạn mức để mua",
        "Нет доступных пакетов кредитов",
        "اعتباری برای خرید موجود نیست",
    ],
    access: [
        "已有账户沿用当前节点组、速度和设备限制；首次购买按所选额度规格开通。",
        "既有帳戶沿用目前節點群組、速度與裝置限制；首次購買按所選額度規格開通。",
        "Existing accounts keep their node group, speed and device limits. First-time access uses the selected credit package.",
        "既存アカウントのノードグループ・速度・端末制限は維持されます。初回は選択したパッケージが適用されます。",
        "기존 계정의 노드 그룹, 속도 및 기기 제한은 유지됩니다. 최초 이용 시 선택한 패키지를 적용합니다.",
        "Tài khoản hiện có giữ nhóm máy chủ, giới hạn tốc độ và thiết bị. Lần đầu áp dụng gói hạn mức đã chọn.",
        "Текущая группа узлов, скорость и лимит устройств сохраняются. При первом подключении применяются условия выбранного пакета.",
        "گروه گره، سرعت و محدودیت دستگاه حساب موجود حفظ می‌شود. دسترسی اولیه بر اساس بسته انتخابی است.",
    ],
    checkout: [
        "继续结算",
        "繼續結帳",
        "Continue to checkout",
        "お支払いへ",
        "결제 진행",
        "Tiếp tục thanh toán",
        "Перейти к оплате",
        "ادامه پرداخت",
    ],
    resetAt: [
        "计划重置时间：{{date}}",
        "預定重設時間：{{date}}",
        "Scheduled reset: {{date}}",
        "リセット予定：{{date}}",
        "예정된 초기화: {{date}}",
        "Đặt lại dự kiến: {{date}}",
        "Плановый сброс: {{date}}",
        "بازنشانی برنامه‌ریزی‌شده: {{date}}",
    ],
    noReset: [
        "当前有效期内无自动重置",
        "目前有效期內無自動重設",
        "No automatic reset before expiry",
        "有効期限まで自動リセットはありません",
        "만료 전 자동 초기화 없음",
        "Không tự đặt lại trước khi hết hạn",
        "До окончания срока автосброса нет",
        "تا پایان اعتبار، بازنشانی خودکار ندارد",
    ],
    noPlanTitle: [
        "暂无有效套餐",
        "暫無有效方案",
        "No active plan",
        "有効なプランなし",
        "활성 요금제 없음",
        "Không có gói còn hạn",
        "Нет активного тарифа",
        "طرح فعالی وجود ندارد",
    ],
    noPlan: [
        "当前没有有效套餐，可直接使用额度。",
        "目前沒有有效方案，可直接使用額度。",
        "No active plan. Credits can be used independently.",
        "有効なプランはありません。クレジットは単独で使えます。",
        "활성 요금제가 없어도 크레딧을 사용할 수 있습니다.",
        "Không có gói còn hạn. Có thể dùng hạn mức độc lập.",
        "Нет активного тарифа. Кредиты доступны самостоятельно.",
        "طرح فعالی وجود ندارد. اعتبار به‌صورت مستقل قابل استفاده است.",
    ],
    back: [
        "返回账单",
        "返回帳單",
        "Back to billing",
        "請求へ戻る",
        "청구로 돌아가기",
        "Quay lại hóa đơn",
        "Назад к счетам",
        "بازگشت به صورتحساب",
    ],
    cancelledHelp: [
        "此订单已关闭，无需继续支付。",
        "此訂單已關閉，無需繼續付款。",
        "This order is closed. No further payment is needed.",
        "この注文は終了しています。支払いは不要です。",
        "종료된 주문입니다. 추가 결제가 필요하지 않습니다.",
        "Đơn đã đóng. Không cần thanh toán tiếp.",
        "Заказ закрыт. Дальнейшая оплата не требуется.",
        "این سفارش بسته شده است. پرداخت دیگری لازم نیست.",
    ],
    credited: [
        "额度已到账，可在使用情况中查看。",
        "額度已入帳，可在使用情況中查看。",
        "Credits added. View your balance in Usage.",
        "クレジットを追加しました。利用状況で確認できます。",
        "크레딧이 충전되었습니다. 사용 현황에서 확인하세요.",
        "Đã cộng hạn mức. Xem số dư trong mục sử dụng.",
        "Кредиты зачислены. Остаток доступен в разделе использования.",
        "اعتبار اضافه شد. موجودی را در بخش مصرف ببینید.",
    ],
    deposited: [
        "充值已到账，可在账单中查看余额。",
        "儲值已入帳，可在帳單中查看餘額。",
        "Top-up received. View your balance in Billing.",
        "チャージ完了。請求画面で残高を確認できます。",
        "충전이 완료되었습니다. 청구에서 잔액을 확인하세요.",
        "Đã nạp tiền. Xem số dư trong hóa đơn.",
        "Пополнение зачислено. Баланс доступен в счетах.",
        "شارژ انجام شد. موجودی را در صورتحساب ببینید.",
    ],
    paid: [
        "实付金额",
        "實付金額",
        "Amount paid",
        "支払金額",
        "결제 금액",
        "Số tiền đã trả",
        "Оплачено",
        "مبلغ پرداخت‌شده",
    ],
    quote: [
        "原应付金额",
        "原應付金額",
        "Original amount due",
        "元の請求額",
        "원래 결제 예정 금액",
        "Số tiền dự kiến ban đầu",
        "Первоначальная сумма",
        "مبلغ اولیه قابل پرداخت",
    ],
    created: [
        "创建时间",
        "建立時間",
        "Created",
        "作成日時",
        "생성 시각",
        "Ngày tạo",
        "Создан",
        "زمان ایجاد",
    ],
    paidAt: [
        "支付时间",
        "付款時間",
        "Paid at",
        "支払日時",
        "결제 시각",
        "Ngày thanh toán",
        "Дата оплаты",
        "زمان پرداخت",
    ],
    balanceReturned: [
        "已返还抵扣余额",
        "已退還抵扣餘額",
        "Balance deduction returned",
        "残高引落し返金済み",
        "차감 잔액 반환됨",
        "Đã hoàn số dư khấu trừ",
        "Списанный баланс возвращён",
        "موجودی کسرشده بازگردانده شد",
    ],
    applied: [
        "此订单已折抵至后续套餐订单。",
        "此訂單已折抵至後續方案訂單。",
        "This order was applied toward a subsequent plan order.",
        "この注文は後続のプラン注文に充当されました。",
        "이 주문은 이후 요금제 주문에 상계되었습니다.",
        "Đơn này đã được khấu trừ vào đơn gói sau đó.",
        "Этот заказ зачтён в последующий заказ тарифа.",
        "این سفارش در سفارش بعدی طرح منظور شده است.",
    ],
    creditOrder: [
        "额度 · {{amount}}",
        "額度 · {{amount}}",
        "Credits · {{amount}}",
        "クレジット · {{amount}}",
        "크레딧 · {{amount}}",
        "Hạn mức · {{amount}}",
        "Кредиты · {{amount}}",
        "اعتبار · {{amount}}",
    ],
} as const;
[
    "zh-CN",
    "zh-TW",
    "en-US",
    "ja-JP",
    "ko-KR",
    "vi-VN",
    "ru-RU",
    "fa-IR",
].forEach((code, index) =>
    i18n.addResourceBundle(
        code,
        "credits",
        Object.fromEntries(
            Object.entries(creditCopy).map(([key, values]) => [
                key,
                values[index],
            ]),
        ),
    ),
);
export const c = (
    key: keyof typeof creditCopy,
    values?: Record<string, unknown>,
): string => String(i18n.t(key, { ns: "credits", ...values }));
export function minuteDate(value: unknown, timezone?: string): string {
    if (!value || !Number.isFinite(Number(value))) return "—";
    return new Intl.DateTimeFormat(locale(), {
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
        hourCycle: "h23",
        ...(timezone
            ? { timeZone: timezone, timeZoneName: "short" as const }
            : {}),
    }).format(new Date(Number(value) * 1000));
}
