import i18n from "./i18n";
export const experienceCopy = {
    quota: [
        "套餐使用额度",
        "套餐使用額度",
        "Plan allowance",
        "プランの利用枠",
        "요금제 사용 한도",
        "Hạn mức gói",
        "Лимит тарифа",
        "سهمیه طرح",
    ],
    remaining: [
        "剩余",
        "剩餘",
        "remaining",
        "残り",
        "남음",
        "còn lại",
        "осталось",
        "باقی‌مانده",
    ],
    resetDays: [
        "距下次重置约 {{count}} 天",
        "距下次重置約 {{count}} 天",
        "Next reset in about {{count}} days",
        "次のリセットまで約 {{count}} 日",
        "다음 초기화까지 약 {{count}}일",
        "Đặt lại sau khoảng {{count}} ngày",
        "До сброса около {{count}} дней",
        "حدود {{count}} روز تا بازنشانی",
    ],
    noReset: [
        "暂无定期重置信息",
        "暫無定期重置資訊",
        "No scheduled reset information",
        "定期リセット情報はありません",
        "정기 초기화 정보 없음",
        "Chưa có thông tin đặt lại định kỳ",
        "Нет данных о плановом сбросе",
        "اطلاعات بازنشانی دوره‌ای موجود نیست",
    ],
    usageAnalysis: [
        "使用分析",
        "使用分析",
        "Usage analysis",
        "利用状況",
        "사용량 분석",
        "Phân tích sử dụng",
        "Анализ использования",
        "تحلیل مصرف",
    ],
    month: [
        "本月",
        "本月",
        "This month",
        "今月",
        "이번 달",
        "Tháng này",
        "Этот месяц",
        "این ماه",
    ],
    week: [
        "近 7 天",
        "近 7 天",
        "Last 7 days",
        "直近7日",
        "최근 7일",
        "7 ngày qua",
        "Последние 7 дней",
        "۷ روز گذشته",
    ],
    dailyUsage: [
        "每日用量",
        "每日用量",
        "Daily usage",
        "日別の利用量",
        "일일 사용량",
        "Sử dụng hằng ngày",
        "Расход по дням",
        "مصرف روزانه",
    ],
    monthOnly: [
        "展示本月上传与下载用量，按日汇总。",
        "顯示本月上傳與下載用量，按日彙總。",
        "Daily upload and download totals for this month.",
        "今月のアップロードとダウンロードを日別に集計。",
        "이번 달 업로드 및 다운로드의 일별 합계입니다.",
        "Tổng tải lên và tải xuống theo ngày trong tháng này.",
        "Загрузка и отдача за этот месяц, по дням.",
        "مجموع روزانه بارگذاری و دریافت این ماه.",
    ],
    depositAmount: [
        "充值金额（{{currency}}）",
        "儲值金額（{{currency}}）",
        "Top-up amount ({{currency}})",
        "チャージ金額（{{currency}}）",
        "충전 금액 ({{currency}})",
        "Số tiền nạp ({{currency}})",
        "Сумма пополнения ({{currency}})",
        "مبلغ افزایش اعتبار ({{currency}})",
    ],
    transferAmount: [
        "转入余额金额（{{currency}}）",
        "轉入餘額金額（{{currency}}）",
        "Transfer to balance ({{currency}})",
        "残高への移行金額（{{currency}}）",
        "잔액으로 이체할 금액 ({{currency}})",
        "Chuyển vào số dư ({{currency}})",
        "Перевод на баланс ({{currency}})",
        "انتقال به موجودی ({{currency}})",
    ],
    wechat: [
        "微信",
        "微信",
        "WeChat",
        "WeChat",
        "WeChat",
        "WeChat",
        "WeChat",
        "WeChat",
    ],
    qq: ["QQ", "QQ", "QQ", "QQ", "QQ", "QQ", "QQ", "QQ"],
    weibo: [
        "微博",
        "微博",
        "Weibo",
        "Weibo",
        "Weibo",
        "Weibo",
        "Weibo",
        "Weibo",
    ],
    deviceLimit: [
        "设备数限制",
        "裝置數限制",
        "Device limit",
        "デバイス数の上限",
        "기기 수 제한",
        "Giới hạn thiết bị",
        "Лимит устройств",
        "محدودیت دستگاه‌ها",
    ],
    registerClosed: [
        "注册暂未开放",
        "註冊暫未開放",
        "Registration is currently closed",
        "現在、新規登録はできません",
        "현재 가입이 종료되었습니다",
        "Hiện chưa mở đăng ký",
        "Регистрация сейчас закрыта",
        "ثبت‌نام در حال حاضر بسته است",
    ],
    next: [
        "继续",
        "繼續",
        "Continue",
        "続ける",
        "계속",
        "Tiếp tục",
        "Продолжить",
        "ادامه",
    ],
    verify: [
        "验证邮箱",
        "驗證信箱",
        "Verify your email",
        "メールを確認",
        "이메일 인증",
        "Xác minh email",
        "Подтвердите почту",
        "تأیید ایمیل",
    ],
    review: [
        "确认账户信息",
        "確認帳戶資訊",
        "Review your account",
        "アカウントを確認",
        "계정 정보 확인",
        "Xác nhận tài khoản",
        "Проверьте данные",
        "بررسی حساب",
    ],
    edit: [
        "修改账户信息",
        "修改帳戶資訊",
        "Edit account details",
        "情報を変更",
        "정보 수정",
        "Sửa thông tin",
        "Изменить данные",
        "ویرایش اطلاعات",
    ],
    verifyHelp: [
        "输入邮件中的 6 位验证码；未收到请检查垃圾邮件或稍后重发。",
        "輸入郵件中的 6 位驗證碼；未收到請檢查垃圾郵件或稍後重發。",
        "Enter the 6-digit email code. Check spam or resend if needed.",
        "メールの6桁のコードを入力。迷惑メールもご確認ください。",
        "이메일의 6자리 코드를 입력하세요. 스팸함도 확인하세요.",
        "Nhập mã 6 chữ số trong email. Kiểm tra thư rác hoặc gửi lại.",
        "Введите код из 6 цифр. Проверьте спам или отправьте повторно.",
        "کد ۶ رقمی ایمیل را وارد کنید. پوشه هرزنامه را بررسی کنید.",
    ],
    codeExpiry: [
        "验证码有效期 5 分钟。",
        "驗證碼有效期 5 分鐘。",
        "The code expires in 5 minutes.",
        "コードは5分間有効です。",
        "코드는 5분간 유효합니다.",
        "Mã có hiệu lực trong 5 phút.",
        "Код действителен 5 минут.",
        "کد تا ۵ دقیقه معتبر است.",
    ],
    sent: [
        "验证码已发送至 {{email}}",
        "驗證碼已寄送至 {{email}}",
        "Code sent to {{email}}",
        "{{email}} にコードを送信しました",
        "{{email}}로 코드를 보냈습니다",
        "Đã gửi mã đến {{email}}",
        "Код отправлен на {{email}}",
        "کد به {{email}} ارسال شد",
    ],
    create: [
        "验证并创建账户",
        "驗證並建立帳戶",
        "Verify and create account",
        "確認してアカウントを作成",
        "인증 후 계정 만들기",
        "Xác minh và tạo tài khoản",
        "Подтвердить и создать аккаунт",
        "تأیید و ایجاد حساب",
    ],
    strength: [
        "密码强度",
        "密碼強度",
        "Password strength",
        "パスワードの強度",
        "비밀번호 강도",
        "Độ mạnh mật khẩu",
        "Надёжность пароля",
        "قدرت گذرواژه",
    ],
    weak: ["较弱", "較弱", "Weak", "弱い", "약함", "Yếu", "Слабый", "ضعیف"],
    fair: [
        "一般",
        "一般",
        "Fair",
        "普通",
        "보통",
        "Trung bình",
        "Средний",
        "متوسط",
    ],
    strong: [
        "较强",
        "較強",
        "Strong",
        "強い",
        "강함",
        "Mạnh",
        "Сильный",
        "قوی",
    ],
    passwordHelp: [
        "至少 8 个字符，请勿重复使用其他网站的密码。",
        "至少 8 個字元，請勿重複使用其他網站的密碼。",
        "Use at least 8 characters and a password unique to this account.",
        "8文字以上で、他のサイトと異なるパスワードを使用。",
        "8자 이상으로 다른 사이트와 다른 비밀번호를 사용하세요.",
        "Dùng ít nhất 8 ký tự, không dùng lại mật khẩu của trang khác.",
        "Не менее 8 символов; не используйте пароль от другого сайта.",
        "حداقل ۸ نویسه؛ از گذرواژه سایت‌های دیگر استفاده نکنید.",
    ],
    resetDone: [
        "密码已更新，请重新登录。",
        "密碼已更新，請重新登入。",
        "Password updated. Sign in again.",
        "パスワードを更新しました。再度ログインしてください。",
        "비밀번호가 변경되었습니다. 다시 로그인하세요.",
        "Đã cập nhật mật khẩu. Vui lòng đăng nhập lại.",
        "Пароль обновлён. Войдите снова.",
        "گذرواژه به‌روز شد. دوباره وارد شوید.",
    ],
    authIntro: [
        "让 AI 工具，更顺畅地工作。",
        "讓 AI 工具，更順暢地工作。",
        "Make your AI tools work more smoothly.",
        "AIツールを、もっと快適に。",
        "AI 도구를 더 편리하게 사용하세요.",
        "Sử dụng công cụ AI thuận tiện hơn.",
        "Пользуйтесь ИИ удобнее.",
        "از ابزارهای هوش مصنوعی روان‌تر استفاده کنید.",
    ],
    authDetail: [
        "从设备配置到使用帮助，在一个地方轻松完成。",
        "從裝置設定到使用協助，在一個地方輕鬆完成。",
        "Device setup and helpful guidance, all in one place.",
        "デバイスの設定から使い方まで、一か所で。",
        "기기 설정부터 사용 안내까지 한곳에서.",
        "Cài đặt thiết bị và hướng dẫn sử dụng trong một nơi.",
        "Настройка устройств и помощь в одном месте.",
        "تنظیم دستگاه و راهنمای استفاده، در یک جا.",
    ],
    recommended: [
        "适合当前设备",
        "適合目前裝置",
        "For this device",
        "このデバイス向け",
        "현재 기기에 적합",
        "Cho thiết bị này",
        "Для этого устройства",
        "برای این دستگاه",
    ],
    allClients: [
        "所有客户端",
        "所有用戶端",
        "All clients",
        "すべてのクライアント",
        "모든 클라이언트",
        "Tất cả ứng dụng",
        "Все приложения",
        "همه برنامه‌ها",
    ],
    deviceHint: [
        "按设备推荐，无法检测是否已安装应用。",
        "依裝置推薦，無法偵測是否已安裝應用程式。",
        "Suggested for your device; installed apps cannot be detected.",
        "デバイスに応じた提案です。インストール済みかは確認できません。",
        "기기에 따른 추천이며 설치 여부는 확인할 수 없습니다.",
        "Gợi ý theo thiết bị; không thể kiểm tra ứng dụng đã cài.",
        "Рекомендации по устройству; наличие приложения не проверяется.",
        "پیشنهاد بر اساس دستگاه است؛ نصب بودن برنامه قابل تشخیص نیست.",
    ],
    browserTitle: [
        "请在手机浏览器中打开",
        "請在手機瀏覽器中開啟",
        "Open in your phone’s browser",
        "スマートフォンのブラウザで開く",
        "휴대폰 브라우저에서 여세요",
        "Mở bằng trình duyệt trên điện thoại",
        "Откройте в браузере телефона",
        "در مرورگر گوشی باز کنید",
    ],
    browserHelp: [
        "当前是 {{app}} 内置浏览器。请点击右上角菜单，选择“在浏览器中打开”，或复制地址到 Safari / Chrome。",
        "目前是 {{app}} 內建瀏覽器。請點選右上角選單，選擇在瀏覽器中開啟，或複製網址至 Safari / Chrome。",
        "You are in {{app}}. Use its top-right menu to open this page in Safari / Chrome, or copy the address.",
        "{{app}} の内蔵ブラウザです。右上のメニューから Safari / Chrome で開くか、URLをコピーしてください。",
        "{{app}} 내장 브라우저입니다. 오른쪽 위 메뉴에서 Safari / Chrome으로 열거나 주소를 복사하세요.",
        "Bạn đang dùng trình duyệt trong {{app}}. Dùng menu trên cùng để mở bằng Safari / Chrome hoặc sao chép địa chỉ.",
        "Это встроенный браузер {{app}}. Через меню справа сверху откройте страницу в Safari / Chrome или скопируйте адрес.",
        "این مرورگر داخلی {{app}} است. از منوی بالا در Safari / Chrome باز کنید یا نشانی را کپی کنید.",
    ],
    browserReason: [
        "应用内浏览器可能无法打开客户端或完成支付跳转。",
        "應用程式內建瀏覽器可能無法開啟用戶端或完成付款跳轉。",
        "In-app browsers may block client imports and payment redirects.",
        "内蔵ブラウザではアプリの起動や決済への移動が制限される場合があります。",
        "내장 브라우저는 앱 실행 및 결제 이동을 제한할 수 있습니다.",
        "Trình duyệt trong ứng dụng có thể chặn mở ứng dụng hoặc chuyển trang thanh toán.",
        "Встроенный браузер может блокировать импорт и переход к оплате.",
        "مرورگر داخلی ممکن است ورود به برنامه و انتقال به پرداخت را مسدود کند.",
    ],
    copyAddress: [
        "复制页面地址",
        "複製頁面網址",
        "Copy page address",
        "ページのURLをコピー",
        "페이지 주소 복사",
        "Sao chép địa chỉ trang",
        "Скопировать адрес",
        "کپی نشانی صفحه",
    ],
    account: [
        "账户菜单",
        "帳戶選單",
        "Account menu",
        "アカウントメニュー",
        "계정 메뉴",
        "Menu tài khoản",
        "Меню аккаунта",
        "منوی حساب",
    ],
    activePlan: [
        "当前套餐：{{plan}}",
        "目前方案：{{plan}}",
        "Current plan: {{plan}}",
        "現在のプラン：{{plan}}",
        "현재 요금제: {{plan}}",
        "Gói hiện tại: {{plan}}",
        "Текущий тариф: {{plan}}",
        "طرح فعلی: {{plan}}",
    ],
    noPlan: [
        "尚无有效套餐",
        "尚無有效方案",
        "No active plan",
        "有効なプランがありません",
        "이용 가능한 요금제 없음",
        "Chưa có gói còn hiệu lực",
        "Нет действующего тарифа",
        "طرح فعالی ندارید",
    ],
    usage: [
        "使用详情",
        "使用詳情",
        "Usage details",
        "利用状況",
        "사용 정보",
        "Chi tiết sử dụng",
        "Статистика использования",
        "جزئیات استفاده",
    ],
    connectionHelp: [
        "配置好设备，开始使用 AI 工具。",
        "設定好裝置，開始使用 AI 工具。",
        "Set up your device and start using AI tools.",
        "デバイスを設定してAIツールを使いましょう。",
        "기기를 설정하고 AI 도구를 사용하세요.",
        "Cài đặt thiết bị và bắt đầu dùng công cụ AI.",
        "Настройте устройство и начните пользоваться ИИ.",
        "دستگاه را تنظیم کنید و از ابزارهای هوش مصنوعی استفاده کنید.",
    ],
    connectionDetail: [
        "订阅状态、设备导入与使用帮助，都在这里。",
        "訂閱狀態、裝置匯入與使用協助，都在這裡。",
        "Plan status, device setup and help, right here.",
        "プランの状態、デバイス設定、ヘルプをここで確認。",
        "요금제 상태, 기기 설정과 도움말을 한곳에서.",
        "Trạng thái gói, cài đặt thiết bị và trợ giúp tại đây.",
        "Статус тарифа, настройка и помощь — здесь.",
        "وضعیت طرح، تنظیم دستگاه و راهنما در همین‌جا.",
    ],
    refreshing: [
        "正在更新数据…",
        "正在更新資料…",
        "Updating…",
        "更新中…",
        "업데이트 중…",
        "Đang cập nhật…",
        "Обновление…",
        "در حال به‌روزرسانی…",
    ],
    manage: [
        "更多订阅操作",
        "更多訂閱操作",
        "More subscription options",
        "その他の操作",
        "추가 구독 옵션",
        "Thêm tùy chọn gói",
        "Другие действия",
        "گزینه‌های بیشتر اشتراک",
    ],
    nodes: [
        "连接信息与可用节点",
        "連線資訊與可用節點",
        "Connection details and available servers",
        "接続情報と利用可能なサーバー",
        "연결 정보 및 이용 가능한 서버",
        "Thông tin kết nối và máy chủ khả dụng",
        "Подключение и доступные серверы",
        "اطلاعات اتصال و سرورهای موجود",
    ],
    stepAccount: [
        "账户信息",
        "帳戶資訊",
        "Account details",
        "アカウント情報",
        "계정 정보",
        "Thông tin tài khoản",
        "Данные аккаунта",
        "اطلاعات حساب",
    ],
    stepVerify: [
        "邮箱验证",
        "信箱驗證",
        "Email verification",
        "メール確認",
        "이메일 인증",
        "Xác minh email",
        "Подтверждение почты",
        "تأیید ایمیل",
    ],
    freeRegister: [
        "创建账户免费，付费操作前会显示费用明细。",
        "建立帳戶免費，付費操作前會顯示費用明細。",
        "Creating an account is free. Charges are shown before any paid action.",
        "アカウント作成は無料です。有料操作の前に料金を表示します。",
        "계정 생성은 무료이며 결제 전 비용이 표시됩니다.",
        "Tạo tài khoản miễn phí. Chi phí được hiển thị trước khi thanh toán.",
        "Регистрация бесплатна. Стоимость показывается до оплаты.",
        "ایجاد حساب رایگان است. هزینه‌ها پیش از پرداخت نمایش داده می‌شوند.",
    ],
} as const;
[
    "zh-CN",
    "zh-TW",
    "en-US",
    "ja-JP",
    "ko-KR",
    "vi-VN",
    "ru-RU",
    "fa-IR",
].forEach((code, index) =>
    i18n.addResourceBundle(
        code,
        "experience",
        Object.fromEntries(
            Object.entries(experienceCopy).map(([key, values]) => [
                key,
                values[index],
            ]),
        ),
    ),
);
export const e = (
    key: keyof typeof experienceCopy,
    values?: Record<string, unknown>,
): string => String(i18n.t(key, { ns: "experience", ...values }));
