import i18n from "./i18n";
export const experienceCopy = {
    newTitle: [
        "欢迎，开始设置你的 AI 使用环境",
        "歡迎，開始設定你的 AI 使用環境",
        "Welcome. Set up your AI workspace",
        "AI の利用環境を設定しましょう",
        "AI 사용 환경을 설정하세요",
        "Chào mừng. Thiết lập môi trường AI",
        "Настройте среду для работы с ИИ",
        "محیط استفاده از هوش مصنوعی را آماده کنید",
    ],
    newDetail: [
        "账户已准备好。选择套餐后，再为设备导入配置。",
        "帳戶已準備好。選擇套餐後，再為裝置匯入設定。",
        "Your account is ready. Choose a plan, then configure your device.",
        "アカウントの準備ができました。プランを選び、端末を設定してください。",
        "계정이 준비되었습니다. 요금제를 선택한 후 기기를 설정하세요.",
        "Tài khoản đã sẵn sàng. Chọn gói rồi cấu hình thiết bị.",
        "Аккаунт готов. Выберите тариф и настройте устройство.",
        "حساب آماده است. یک طرح انتخاب کنید، سپس دستگاه را تنظیم کنید.",
    ],
    expiredTitle: [
        "订阅已到期",
        "訂閱已到期",
        "Your plan has expired",
        "プランの有効期限が切れました",
        "구독 기간이 만료되었습니다",
        "Gói đã hết hạn",
        "Срок подписки истёк",
        "اشتراک منقضی شده است",
    ],
    expiredDetail: [
        "续订或选择新的套餐后，即可继续配置设备。你的账户和订单记录仍可查看。",
        "續訂或選擇新套餐後，即可繼續設定裝置。帳戶和訂單紀錄仍可查看。",
        "Renew or choose a new plan to continue. Your account and orders remain accessible.",
        "更新または新しいプランを選んでください。アカウントと注文履歴は確認できます。",
        "갱신하거나 새 요금제를 선택하세요. 계정과 주문 내역은 계속 확인할 수 있습니다.",
        "Gia hạn hoặc chọn gói mới. Tài khoản và lịch sử đơn hàng vẫn truy cập được.",
        "Продлите или выберите новый тариф. Аккаунт и заказы по-прежнему доступны.",
        "تمدید کنید یا طرح جدیدی انتخاب کنید. حساب و سفارش‌ها همچنان در دسترس هستند.",
    ],
    renew: [
        "续订或选择套餐",
        "續訂或選擇套餐",
        "Renew or choose a plan",
        "更新・プラン選択",
        "갱신 또는 요금제 선택",
        "Gia hạn hoặc chọn gói",
        "Продлить или выбрать тариф",
        "تمدید یا انتخاب طرح",
    ],
    bannedTitle: [
        "账户已被封禁",
        "帳戶已被封禁",
        "Account suspended",
        "アカウントが停止されています",
        "계정이 정지되었습니다",
        "Tài khoản bị đình chỉ",
        "Аккаунт заблокирован",
        "حساب مسدود شده است",
    ],
    bannedDetail: [
        "当前账户无法使用服务。请联系管理员核实原因；购买套餐或重置密码不会解除封禁。",
        "目前帳戶無法使用服務。請聯絡管理員確認原因；購買套餐或重設密碼不會解除封禁。",
        "This account cannot use the service. Contact the administrator; buying a plan or resetting a password will not lift the suspension.",
        "サービスを利用できません。管理者にお問い合わせください。購入やパスワード変更では解除されません。",
        "서비스를 이용할 수 없습니다. 관리자에게 문의하세요. 구매나 비밀번호 변경으로 정지가 해제되지 않습니다.",
        "Không thể sử dụng dịch vụ. Liên hệ quản trị viên; mua gói hoặc đổi mật khẩu không gỡ đình chỉ.",
        "Сервис недоступен. Обратитесь к администратору; покупка тарифа или смена пароля не снимает блокировку.",
        "امکان استفاده از سرویس نیست. با مدیر تماس بگیرید؛ خرید طرح یا تغییر گذرواژه مسدودی را رفع نمی‌کند.",
    ],
    contactAdmin: [
        "联系管理员",
        "聯絡管理員",
        "Contact administrator",
        "管理者に連絡",
        "관리자 문의",
        "Liên hệ quản trị viên",
        "Связаться с администратором",
        "تماس با مدیر",
    ],
    exhausted: [
        "本期额度已用尽。请检查套餐的重置或续订选项。",
        "本期額度已用盡。請查看套餐的重置或續訂選項。",
        "Your allowance is used up. Check your plan's reset or renewal options.",
        "利用枠を使い切りました。リセットや更新の選択肢をご確認ください。",
        "사용 한도를 소진했습니다. 초기화 또는 갱신 옵션을 확인하세요.",
        "Đã hết hạn mức. Xem tùy chọn đặt lại hoặc gia hạn.",
        "Лимит исчерпан. Проверьте возможность сброса или продления.",
        "سهمیه مصرف شده است. گزینه‌های بازنشانی یا تمدید طرح را بررسی کنید.",
    ],
    unavailable: [
        "当前套餐尚无可用额度，请联系管理员或查看套餐选项。",
        "目前套餐尚無可用額度，請聯絡管理員或查看套餐選項。",
        "This plan has no available allowance. Contact support or review plan options.",
        "利用枠がありません。管理者またはプランをご確認ください。",
        "사용 가능한 한도가 없습니다. 관리자 또는 요금제를 확인하세요.",
        "Gói chưa có hạn mức khả dụng. Liên hệ hỗ trợ hoặc xem gói.",
        "У тарифа нет доступного лимита. Обратитесь в поддержку или проверьте тариф.",
        "طرح سهمیه قابل استفاده ندارد. با پشتیبانی تماس بگیرید یا طرح را بررسی کنید.",
    ],
    activeTitle: [
        "订阅有效",
        "訂閱有效",
        "Plan active",
        "プラン有効",
        "구독 유효",
        "Gói còn hiệu lực",
        "Подписка активна",
        "اشتراک فعال",
    ],
    quota: [
        "套餐使用额度",
        "套餐使用額度",
        "Plan allowance",
        "プランの利用枠",
        "요금제 사용 한도",
        "Hạn mức gói",
        "Лимит тарифа",
        "سهمیه طرح",
    ],
    remaining: [
        "剩余",
        "剩餘",
        "remaining",
        "残り",
        "남음",
        "còn lại",
        "осталось",
        "باقی‌مانده",
    ],
    resetDays: [
        "距下次重置约 {{count}} 天",
        "距下次重置約 {{count}} 天",
        "Next reset in about {{count}} days",
        "次のリセットまで約 {{count}} 日",
        "다음 초기화까지 약 {{count}}일",
        "Đặt lại sau khoảng {{count}} ngày",
        "До сброса около {{count}} дней",
        "حدود {{count}} روز تا بازنشانی",
    ],
    noReset: [
        "暂无定期重置信息",
        "暫無定期重置資訊",
        "No scheduled reset information",
        "定期リセット情報はありません",
        "정기 초기화 정보 없음",
        "Chưa có thông tin đặt lại định kỳ",
        "Нет данных о плановом сбросе",
        "اطلاعات بازنشانی دوره‌ای موجود نیست",
    ],
    usageAnalysis: [
        "使用分析",
        "使用分析",
        "Usage analysis",
        "利用状況",
        "사용량 분석",
        "Phân tích sử dụng",
        "Анализ использования",
        "تحلیل مصرف",
    ],
    month: [
        "本月",
        "本月",
        "This month",
        "今月",
        "이번 달",
        "Tháng này",
        "Этот месяц",
        "این ماه",
    ],
    week: [
        "近 7 天",
        "近 7 天",
        "Last 7 days",
        "直近7日",
        "최근 7일",
        "7 ngày qua",
        "Последние 7 дней",
        "۷ روز گذشته",
    ],
    dailyUsage: [
        "每日用量",
        "每日用量",
        "Daily usage",
        "日別の利用量",
        "일일 사용량",
        "Sử dụng hằng ngày",
        "Расход по дням",
        "مصرف روزانه",
    ],
    monthOnly: [
        "展示本月上传与下载用量，按日汇总。",
        "顯示本月上傳與下載用量，按日彙總。",
        "Daily upload and download totals for this month.",
        "今月のアップロードとダウンロードを日別に集計。",
        "이번 달 업로드 및 다운로드의 일별 합계입니다.",
        "Tổng tải lên và tải xuống theo ngày trong tháng này.",
        "Загрузка и отдача за этот месяц, по дням.",
        "مجموع روزانه بارگذاری و دریافت این ماه.",
    ],
    depositAmount: [
        "充值金额（{{currency}}）",
        "儲值金額（{{currency}}）",
        "Top-up amount ({{currency}})",
        "チャージ金額（{{currency}}）",
        "충전 금액 ({{currency}})",
        "Số tiền nạp ({{currency}})",
        "Сумма пополнения ({{currency}})",
        "مبلغ افزایش اعتبار ({{currency}})",
    ],
    transferAmount: [
        "转入余额金额（{{currency}}）",
        "轉入餘額金額（{{currency}}）",
        "Transfer to balance ({{currency}})",
        "残高への移行金額（{{currency}}）",
        "잔액으로 이체할 금액 ({{currency}})",
        "Chuyển vào số dư ({{currency}})",
        "Перевод на баланс ({{currency}})",
        "انتقال به موجودی ({{currency}})",
    ],
    wechat: [
        "微信",
        "微信",
        "WeChat",
        "WeChat",
        "WeChat",
        "WeChat",
        "WeChat",
        "WeChat",
    ],
    qq: ["QQ", "QQ", "QQ", "QQ", "QQ", "QQ", "QQ", "QQ"],
    weibo: [
        "微博",
        "微博",
        "Weibo",
        "Weibo",
        "Weibo",
        "Weibo",
        "Weibo",
        "Weibo",
    ],
    deviceLimit: [
        "设备数限制",
        "裝置數限制",
        "Device limit",
        "デバイス数の上限",
        "기기 수 제한",
        "Giới hạn thiết bị",
        "Лимит устройств",
        "محدودیت دستگاه‌ها",
    ],
    registerClosed: [
        "注册暂未开放",
        "註冊暫未開放",
        "Registration is currently closed",
        "現在、新規登録はできません",
        "현재 가입이 종료되었습니다",
        "Hiện chưa mở đăng ký",
        "Регистрация сейчас закрыта",
        "ثبت‌نام در حال حاضر بسته است",
    ],
    next: [
        "继续",
        "繼續",
        "Continue",
        "続ける",
        "계속",
        "Tiếp tục",
        "Продолжить",
        "ادامه",
    ],
    verify: [
        "验证邮箱",
        "驗證信箱",
        "Verify your email",
        "メールを確認",
        "이메일 인증",
        "Xác minh email",
        "Подтвердите почту",
        "تأیید ایمیل",
    ],
    review: [
        "确认账户信息",
        "確認帳戶資訊",
        "Review your account",
        "アカウントを確認",
        "계정 정보 확인",
        "Xác nhận tài khoản",
        "Проверьте данные",
        "بررسی حساب",
    ],
    edit: [
        "修改账户信息",
        "修改帳戶資訊",
        "Edit account details",
        "情報を変更",
        "정보 수정",
        "Sửa thông tin",
        "Изменить данные",
        "ویرایش اطلاعات",
    ],
    verifyHelp: [
        "输入邮件中的 6 位验证码；未收到请检查垃圾邮件或稍后重发。",
        "輸入郵件中的 6 位驗證碼；未收到請檢查垃圾郵件或稍後重發。",
        "Enter the 6-digit email code. Check spam or resend if needed.",
        "メールの6桁のコードを入力。迷惑メールもご確認ください。",
        "이메일의 6자리 코드를 입력하세요. 스팸함도 확인하세요.",
        "Nhập mã 6 chữ số trong email. Kiểm tra thư rác hoặc gửi lại.",
        "Введите код из 6 цифр. Проверьте спам или отправьте повторно.",
        "کد ۶ رقمی ایمیل را وارد کنید. پوشه هرزنامه را بررسی کنید.",
    ],
    codeExpiry: [
        "验证码有效期 5 分钟。",
        "驗證碼有效期 5 分鐘。",
        "The code expires in 5 minutes.",
        "コードは5分間有効です。",
        "코드는 5분간 유효합니다.",
        "Mã có hiệu lực trong 5 phút.",
        "Код действителен 5 минут.",
        "کد تا ۵ دقیقه معتبر است.",
    ],
    sent: [
        "验证码已发送至 {{email}}",
        "驗證碼已寄送至 {{email}}",
        "Code sent to {{email}}",
        "{{email}} にコードを送信しました",
        "{{email}}로 코드를 보냈습니다",
        "Đã gửi mã đến {{email}}",
        "Код отправлен на {{email}}",
        "کد به {{email}} ارسال شد",
    ],
    create: [
        "验证并创建账户",
        "驗證並建立帳戶",
        "Verify and create account",
        "確認してアカウントを作成",
        "인증 후 계정 만들기",
        "Xác minh và tạo tài khoản",
        "Подтвердить и создать аккаунт",
        "تأیید و ایجاد حساب",
    ],
    strength: [
        "密码强度",
        "密碼強度",
        "Password strength",
        "パスワードの強度",
        "비밀번호 강도",
        "Độ mạnh mật khẩu",
        "Надёжность пароля",
        "قدرت گذرواژه",
    ],
    weak: ["较弱", "較弱", "Weak", "弱い", "약함", "Yếu", "Слабый", "ضعیف"],
    fair: [
        "一般",
        "一般",
        "Fair",
        "普通",
        "보통",
        "Trung bình",
        "Средний",
        "متوسط",
    ],
    strong: [
        "较强",
        "較強",
        "Strong",
        "強い",
        "강함",
        "Mạnh",
        "Сильный",
        "قوی",
    ],
    passwordHelp: [
        "至少 8 个字符，请勿重复使用其他网站的密码。",
        "至少 8 個字元，請勿重複使用其他網站的密碼。",
        "Use at least 8 characters and a password unique to this account.",
        "8文字以上で、他のサイトと異なるパスワードを使用。",
        "8자 이상으로 다른 사이트와 다른 비밀번호를 사용하세요.",
        "Dùng ít nhất 8 ký tự, không dùng lại mật khẩu của trang khác.",
        "Не менее 8 символов; не используйте пароль от другого сайта.",
        "حداقل ۸ نویسه؛ از گذرواژه سایت‌های دیگر استفاده نکنید.",
    ],
    resetDone: [
        "密码已更新，请重新登录。",
        "密碼已更新，請重新登入。",
        "Password updated. Sign in again.",
        "パスワードを更新しました。再度ログインしてください。",
        "비밀번호가 변경되었습니다. 다시 로그인하세요.",
        "Đã cập nhật mật khẩu. Vui lòng đăng nhập lại.",
        "Пароль обновлён. Войдите снова.",
        "گذرواژه به‌روز شد. دوباره وارد شوید.",
    ],
    authIntro: [
        "让 AI 工具，更顺畅地工作。",
        "讓 AI 工具，更順暢地工作。",
        "Make your AI tools work more smoothly.",
        "AIツールを、もっと快適に。",
        "AI 도구를 더 편리하게 사용하세요.",
        "Sử dụng công cụ AI thuận tiện hơn.",
        "Пользуйтесь ИИ удобнее.",
        "از ابزارهای هوش مصنوعی روان‌تر استفاده کنید.",
    ],
    authDetail: [
        "从设备配置到使用帮助，在一个地方轻松完成。",
        "從裝置設定到使用協助，在一個地方輕鬆完成。",
        "Device setup and helpful guidance, all in one place.",
        "デバイスの設定から使い方まで、一か所で。",
        "기기 설정부터 사용 안내까지 한곳에서.",
        "Cài đặt thiết bị và hướng dẫn sử dụng trong một nơi.",
        "Настройка устройств и помощь в одном месте.",
        "تنظیم دستگاه و راهنمای استفاده، در یک جا.",
    ],
    recommended: [
        "适合当前设备",
        "適合目前裝置",
        "For this device",
        "このデバイス向け",
        "현재 기기에 적합",
        "Cho thiết bị này",
        "Для этого устройства",
        "برای این دستگاه",
    ],
    allClients: [
        "所有客户端",
        "所有用戶端",
        "All clients",
        "すべてのクライアント",
        "모든 클라이언트",
        "Tất cả ứng dụng",
        "Все приложения",
        "همه برنامه‌ها",
    ],
    deviceHint: [
        "按设备推荐，无法检测是否已安装应用。",
        "依裝置推薦，無法偵測是否已安裝應用程式。",
        "Suggested for your device; installed apps cannot be detected.",
        "デバイスに応じた提案です。インストール済みかは確認できません。",
        "기기에 따른 추천이며 설치 여부는 확인할 수 없습니다.",
        "Gợi ý theo thiết bị; không thể kiểm tra ứng dụng đã cài.",
        "Рекомендации по устройству; наличие приложения не проверяется.",
        "پیشنهاد بر اساس دستگاه است؛ نصب بودن برنامه قابل تشخیص نیست.",
    ],
    browserMenu: [
        "打开页面菜单",
        "開啟頁面選單",
        "Open the page menu",
        "ページメニューを開く",
        "페이지 메뉴 열기",
        "Mở menu của trang",
        "Откройте меню страницы",
        "منوی صفحه را باز کنید",
    ],
    browserMenuDetail: [
        "点击应用的「⋯」或更多按钮，通常位于右上角。",
        "點選應用程式的「⋯」或更多按鈕，通常位於右上角。",
        "Tap the app’s ⋯ or More button, usually in the top-right corner.",
        "通常は右上にある「⋯」またはその他のメニューをタップします。",
        "보통 오른쪽 위에 있는 앱의 ⋯ 또는 더보기 버튼을 누르세요.",
        "Nhấn nút ⋯ hoặc Thêm của ứng dụng, thường ở góc trên bên phải.",
        "Нажмите ⋯ или «Ещё» в приложении, обычно справа вверху.",
        "روی دکمه ⋯ یا «بیشتر» برنامه، معمولاً در بالای صفحه، بزنید.",
    ],
    browserChoose: [
        "选择在浏览器中打开",
        "選擇在瀏覽器中開啟",
        "Choose Open in browser",
        "ブラウザで開くを選ぶ",
        "브라우저에서 열기 선택",
        "Chọn Mở trong trình duyệt",
        "Выберите «Открыть в браузере»",
        "«باز کردن در مرورگر» را انتخاب کنید",
    ],
    browserChooseDetail: [
        "找到「在浏览器中打开」或类似选项，按提示继续。",
        "找到「在瀏覽器中開啟」或類似選項，依提示繼續。",
        "Look for Open in browser or a similar option and follow the prompts.",
        "「ブラウザで開く」などの項目を選び、案内に沿って進めます。",
        "브라우저에서 열기 또는 비슷한 항목을 선택하고 안내를 따르세요.",
        "Tìm mục Mở trong trình duyệt hoặc tùy chọn tương tự rồi làm theo hướng dẫn.",
        "Найдите «Открыть в браузере» или похожий пункт и следуйте подсказкам.",
        "گزینه «باز کردن در مرورگر» یا گزینه‌ای مشابه را پیدا کنید و ادامه دهید.",
    ],
    browserAlternative: [
        "没有找到这个选项？",
        "找不到這個選項？",
        "Can’t find that option?",
        "項目が見つかりませんか？",
        "해당 항목이 없나요?",
        "Không tìm thấy tùy chọn này?",
        "Не нашли этот пункт?",
        "این گزینه را پیدا نمی‌کنید؟",
    ],
    browserPaste: [
        "复制当前页面地址，再打开手机浏览器粘贴访问。",
        "複製目前頁面網址，再開啟手機瀏覽器貼上。",
        "Copy this page’s address, then paste it into your phone’s browser.",
        "このページのURLをコピーし、スマートフォンのブラウザに貼り付けて開きます。",
        "현재 페이지 주소를 복사한 뒤 휴대폰 브라우저에 붙여넣으세요.",
        "Sao chép địa chỉ trang này rồi dán vào trình duyệt điện thoại.",
        "Скопируйте адрес страницы и вставьте его в браузер телефона.",
        "نشانی این صفحه را کپی کنید و در مرورگر گوشی بچسبانید.",
    ],
    browserCopied: [
        "链接已复制。打开手机浏览器，粘贴地址即可继续。",
        "連結已複製。開啟手機瀏覽器，貼上網址即可繼續。",
        "Link copied. Open your phone’s browser and paste the address to continue.",
        "コピーしました。スマートフォンのブラウザにURLを貼り付けて続けてください。",
        "링크를 복사했어요. 휴대폰 브라우저에 주소를 붙여넣어 계속하세요.",
        "Đã sao chép liên kết. Mở trình duyệt điện thoại và dán địa chỉ để tiếp tục.",
        "Ссылка скопирована. Вставьте её в браузер телефона, чтобы продолжить.",
        "پیوند کپی شد. مرورگر گوشی را باز کنید و نشانی را بچسبانید.",
    ],
    browserManual: [
        "手动复制链接",
        "手動複製連結",
        "Copy link manually",
        "URLを手動でコピー",
        "링크 직접 복사",
        "Sao chép liên kết thủ công",
        "Скопировать вручную",
        "کپی دستی پیوند",
    ],
    browserCopyHelp: [
        "自动复制未完成，请长按下方地址并选择复制。",
        "自動複製未完成，請長按下方網址並選擇複製。",
        "Automatic copying failed. Press and hold the address below, then choose Copy.",
        "自動コピーできませんでした。下のURLを長押ししてコピーしてください。",
        "자동 복사가 되지 않았어요. 아래 주소를 길게 누른 뒤 복사를 선택하세요.",
        "Không thể tự động sao chép. Nhấn giữ địa chỉ bên dưới rồi chọn Sao chép.",
        "Не удалось скопировать автоматически. Нажмите и удерживайте адрес ниже, затем выберите «Копировать».",
        "کپی خودکار انجام نشد. نشانی زیر را لمس کنید و نگه دارید، سپس کپی را انتخاب کنید.",
    ],
    browserTitle: [
        "请在手机浏览器中打开",
        "請在手機瀏覽器中開啟",
        "Open in your phone’s browser",
        "スマートフォンのブラウザで開く",
        "휴대폰 브라우저에서 여세요",
        "Mở bằng trình duyệt trên điện thoại",
        "Откройте в браузере телефона",
        "در مرورگر گوشی باز کنید",
    ],
    browserHelp: [
        "当前在 {{app}} 内打开",
        "目前在 {{app}} 內開啟",
        "Opened inside {{app}}",
        "{{app}} 内で開いています",
        "{{app}}에서 열었어요",
        "Đang mở trong {{app}}",
        "Открыто внутри {{app}}",
        "بازشده در {{app}}",
    ],
    browserReason: [
        "为了顺利完成登录、设备配置和支付，请在手机浏览器中继续。",
        "為了順利完成登入、裝置設定與付款，請在手機瀏覽器中繼續。",
        "Continue in your phone’s browser for reliable sign-in, device setup and payment.",
        "ログイン、デバイス設定、お支払いをスムーズに進めるため、スマートフォンのブラウザで続けてください。",
        "로그인, 기기 설정 및 결제를 원활하게 진행하려면 휴대폰 브라우저에서 계속하세요.",
        "Hãy tiếp tục trong trình duyệt điện thoại để đăng nhập, thiết lập thiết bị và thanh toán thuận tiện.",
        "Продолжите в браузере телефона для входа, настройки устройства и оплаты.",
        "برای ورود، تنظیم دستگاه و پرداخت بدون مشکل، در مرورگر گوشی ادامه دهید.",
    ],
    copyAddress: [
        "复制页面地址",
        "複製頁面網址",
        "Copy page address",
        "ページのURLをコピー",
        "페이지 주소 복사",
        "Sao chép địa chỉ trang",
        "Скопировать адрес",
        "کپی نشانی صفحه",
    ],
    account: [
        "账户菜单",
        "帳戶選單",
        "Account menu",
        "アカウントメニュー",
        "계정 메뉴",
        "Menu tài khoản",
        "Меню аккаунта",
        "منوی حساب",
    ],
    activePlan: [
        "当前套餐：{{plan}}",
        "目前方案：{{plan}}",
        "Current plan: {{plan}}",
        "現在のプラン：{{plan}}",
        "현재 요금제: {{plan}}",
        "Gói hiện tại: {{plan}}",
        "Текущий тариф: {{plan}}",
        "طرح فعلی: {{plan}}",
    ],
    noPlan: [
        "尚无有效套餐",
        "尚無有效方案",
        "No active plan",
        "有効なプランがありません",
        "이용 가능한 요금제 없음",
        "Chưa có gói còn hiệu lực",
        "Нет действующего тарифа",
        "طرح فعالی ندارید",
    ],
    usage: [
        "使用详情",
        "使用詳情",
        "Usage details",
        "利用状況",
        "사용 정보",
        "Chi tiết sử dụng",
        "Статистика использования",
        "جزئیات استفاده",
    ],
    connectionHelp: [
        "配置好设备，开始使用 AI 工具。",
        "設定好裝置，開始使用 AI 工具。",
        "Set up your device and start using AI tools.",
        "デバイスを設定してAIツールを使いましょう。",
        "기기를 설정하고 AI 도구를 사용하세요.",
        "Cài đặt thiết bị và bắt đầu dùng công cụ AI.",
        "Настройте устройство и начните пользоваться ИИ.",
        "دستگاه را تنظیم کنید و از ابزارهای هوش مصنوعی استفاده کنید.",
    ],
    connectionDetail: [
        "订阅状态、设备导入与使用帮助，都在这里。",
        "訂閱狀態、裝置匯入與使用協助，都在這裡。",
        "Plan status, device setup and help, right here.",
        "プランの状態、デバイス設定、ヘルプをここで確認。",
        "요금제 상태, 기기 설정과 도움말을 한곳에서.",
        "Trạng thái gói, cài đặt thiết bị và trợ giúp tại đây.",
        "Статус тарифа, настройка и помощь — здесь.",
        "وضعیت طرح، تنظیم دستگاه و راهنما در همین‌جا.",
    ],
    refreshing: [
        "正在更新数据…",
        "正在更新資料…",
        "Updating…",
        "更新中…",
        "업데이트 중…",
        "Đang cập nhật…",
        "Обновление…",
        "در حال به‌روزرسانی…",
    ],
    manage: [
        "更多订阅操作",
        "更多訂閱操作",
        "More subscription options",
        "その他の操作",
        "추가 구독 옵션",
        "Thêm tùy chọn gói",
        "Другие действия",
        "گزینه‌های بیشتر اشتراک",
    ],
    nodes: [
        "连接信息与可用节点",
        "連線資訊與可用節點",
        "Connection details and available servers",
        "接続情報と利用可能なサーバー",
        "연결 정보 및 이용 가능한 서버",
        "Thông tin kết nối và máy chủ khả dụng",
        "Подключение и доступные серверы",
        "اطلاعات اتصال و سرورهای موجود",
    ],
    stepAccount: [
        "账户信息",
        "帳戶資訊",
        "Account details",
        "アカウント情報",
        "계정 정보",
        "Thông tin tài khoản",
        "Данные аккаунта",
        "اطلاعات حساب",
    ],
    stepVerify: [
        "邮箱验证",
        "信箱驗證",
        "Email verification",
        "メール確認",
        "이메일 인증",
        "Xác minh email",
        "Подтверждение почты",
        "تأیید ایمیل",
    ],
    freeRegister: [
        "创建账户免费，付费操作前会显示费用明细。",
        "建立帳戶免費，付費操作前會顯示費用明細。",
        "Creating an account is free. Charges are shown before any paid action.",
        "アカウント作成は無料です。有料操作の前に料金を表示します。",
        "계정 생성은 무료이며 결제 전 비용이 표시됩니다.",
        "Tạo tài khoản miễn phí. Chi phí được hiển thị trước khi thanh toán.",
        "Регистрация бесплатна. Стоимость показывается до оплаты.",
        "ایجاد حساب رایگان است. هزینه‌ها پیش از پرداخت نمایش داده می‌شوند.",
    ],
} as const;
[
    "zh-CN",
    "zh-TW",
    "en-US",
    "ja-JP",
    "ko-KR",
    "vi-VN",
    "ru-RU",
    "fa-IR",
].forEach((code, index) =>
    i18n.addResourceBundle(
        code,
        "experience",
        Object.fromEntries(
            Object.entries(experienceCopy).map(([key, values]) => [
                key,
                values[index],
            ]),
        ),
    ),
);
export const e = (
    key: keyof typeof experienceCopy,
    values?: Record<string, unknown>,
): string => String(i18n.t(key, { ns: "experience", ...values }));
