import i18n from "./i18n";
export const landingCopy = {
    aiTitle: [
        "连接你的 AI 世界",
        "連接你的 AI 世界",
        "Connect to your AI world",
        "あなたの AI の世界へ",
        "나만의 AI 세상으로",
        "Kết nối thế giới AI của bạn",
        "Откройте свой мир ИИ",
        "به دنیای هوش مصنوعی خود متصل شوید",
    ],
    aiIntro: [
        "熟悉的工具，更多可能。",
        "熟悉的工具，更多可能。",
        "Familiar tools. More possibilities.",
        "いつものツールで、可能性を広げる。",
        "익숙한 도구로 더 많은 가능성을.",
        "Công cụ quen thuộc, nhiều khả năng hơn.",
        "Знакомые инструменты. Больше возможностей.",
        "ابزارهای آشنا، امکانات بیشتر.",
    ],
    aiLabel: [
        "探索 AI 服务",
        "探索 AI 服務",
        "Explore AI services",
        "AI サービスを探索",
        "AI 서비스 살펴보기",
        "Khám phá dịch vụ AI",
        "Знакомство с ИИ-сервисами",
        "کاوش خدمات هوش مصنوعی",
    ],
    aiNote: [
        "第三方服务需另行注册，会员权益不包含在内。",
        "第三方服務需另行註冊，不包含會員權益。",
        "Third-party services require separate accounts. Memberships are not included.",
        "各サービスへの登録が別途必要です。有料プランは含まれません。",
        "각 서비스의 계정이 별도로 필요하며 멤버십은 포함되지 않습니다.",
        "Cần tài khoản riêng cho từng dịch vụ. Không bao gồm gói thành viên.",
        "Нужны отдельные аккаунты. Подписки на эти сервисы не включены.",
        "حساب جداگانه لازم است. اشتراک این خدمات شامل نمی‌شود.",
    ],

    scenarioTitle: [
        "把时间留给想做的事",
        "把時間留給想做的事",
        "More time for what matters",
        "やりたいことに、もっと時間を",
        "하고 싶은 일에 더 많은 시간을",
        "Dành thời gian cho điều bạn muốn làm",
        "Больше времени на важное",
        "زمان بیشتر برای کارهای دلخواه",
    ],
    scenarioIntro: [
        "工作、学习与创作，从顺畅的使用环境开始。",
        "工作、學習與創作，從順暢的使用環境開始。",
        "Work, learn and create with a smoother setup.",
        "仕事も学習も創作も、快適な利用環境から。",
        "원활한 사용 환경에서 일하고 배우고 창작하세요.",
        "Làm việc, học tập và sáng tạo với môi trường sử dụng thuận tiện.",
        "Работайте, учитесь и создавайте в удобной среде.",
        "کار، یادگیری و خلق کردن را با محیطی روان‌تر آغاز کنید.",
    ],
    scenario1: [
        "写作与创作",
        "寫作與創作",
        "Writing and creativity",
        "文章作成と創作",
        "글쓰기와 창작",
        "Viết và sáng tạo",
        "Тексты и творчество",
        "نوشتن و خلق کردن",
    ],
    scenario1Text: [
        "构思、润色，让想法更清晰。",
        "構思、潤飾，讓想法更清楚。",
        "Explore ideas and refine your words.",
        "アイデアを広げ、言葉を磨く。",
        "아이디어를 펼치고 표현을 다듬으세요.",
        "Phát triển ý tưởng và trau chuốt câu chữ.",
        "Развивайте идеи и улучшайте формулировки.",
        "ایده‌ها را گسترش دهید و نوشته‌ها را بهبود دهید.",
    ],
    scenario2: [
        "学习与探索",
        "學習與探索",
        "Learning and discovery",
        "学習と探究",
        "학습과 탐색",
        "Học tập và khám phá",
        "Учёба и исследования",
        "یادگیری و کاوش",
    ],
    scenario2Text: [
        "理解新知识，梳理复杂信息。",
        "理解新知識，整理複雜資訊。",
        "Understand new topics and organize information.",
        "新しい知識を理解し、複雑な情報を整理する。",
        "새 지식을 이해하고 복잡한 정보를 정리하세요.",
        "Hiểu kiến thức mới và sắp xếp thông tin phức tạp.",
        "Изучайте новое и упорядочивайте сложную информацию.",
        "موضوعات تازه را درک و اطلاعات پیچیده را مرتب کنید.",
    ],
    scenario3: [
        "编程与工作",
        "程式開發與工作",
        "Coding and work",
        "プログラミングと仕事",
        "코딩과 업무",
        "Lập trình và công việc",
        "Код и работа",
        "برنامه‌نویسی و کار",
    ],
    scenario3Text: [
        "整理思路，让日常任务更顺手。",
        "整理思路，讓日常任務更順手。",
        "Organize your thinking and everyday tasks.",
        "考えを整理し、日々の作業を進める。",
        "생각을 정리하고 일상 업무를 더 수월하게 진행하세요.",
        "Sắp xếp ý tưởng và xử lý công việc hằng ngày.",
        "Структурируйте мысли и повседневные задачи.",
        "افکارتان را سامان دهید و کارهای روزمره را پیش ببرید.",
    ],
    skip: [
        "跳转到主要内容",
        "跳至主要內容",
        "Skip to content",
        "本文へ移動",
        "본문으로 건너뛰기",
        "Chuyển đến nội dung",
        "Перейти к содержимому",
        "رفتن به محتوا",
    ],
    preview: [
        "使用场景",
        "使用情境",
        "Everyday uses",
        "活用シーン",
        "활용 사례",
        "Ứng dụng hằng ngày",
        "Сценарии использования",
        "کاربردهای روزمره",
    ],
    previewNote: [
        "登录后，按设备获取完整配置指引。",
        "登入後，依裝置取得完整設定指引。",
        "Sign in for the complete setup guide for your device.",
        "ログインしてデバイスに合った設定ガイドを確認。",
        "로그인하여 기기에 맞는 전체 설정 안내를 확인하세요.",
        "Đăng nhập để xem hướng dẫn đầy đủ cho thiết bị của bạn.",
        "Войдите, чтобы получить полную инструкцию для устройства.",
        "برای راهنمای کامل تنظیم دستگاه خود وارد شوید.",
    ],
    beforeStart: [
        "开始之前",
        "開始之前",
        "Before you begin",
        "はじめる前に",
        "시작하기 전에",
        "Trước khi bắt đầu",
        "Перед началом",
        "پیش از شروع",
    ],
    terms: [
        "服务条款",
        "服務條款",
        "Terms of service",
        "利用規約",
        "이용약관",
        "Điều khoản dịch vụ",
        "Условия использования",
        "شرایط استفاده",
    ],
    examples: [
        "配置流程",
        "設定流程",
        "How it works",
        "設定の流れ",
        "설정 과정",
        "Cách thiết lập",
        "Как это работает",
        "روش راه‌اندازی",
    ],
    about: [
        "使用帮助",
        "使用協助",
        "How we help",
        "使い方のサポート",
        "사용 지원",
        "Hỗ trợ sử dụng",
        "Помощь",
        "راهنمای استفاده",
    ],
    questions: [
        "常见问题",
        "常見問題",
        "Questions",
        "よくある質問",
        "자주 묻는 질문",
        "Câu hỏi",
        "Вопросы",
        "پرسش‌ها",
    ],
    signIn: [
        "登录",
        "登入",
        "Sign in",
        "ログイン",
        "로그인",
        "Đăng nhập",
        "Войти",
        "ورود",
    ],
    start: [
        "开始配置",
        "開始設定",
        "Start your setup",
        "設定を始める",
        "설정 시작",
        "Bắt đầu thiết lập",
        "Начать настройку",
        "شروع تنظیم",
    ],
    tag: [
        "你的 AI 使用助手",
        "你的 AI 使用助手",
        "Your AI setup companion",
        "AIの利用を支えるアシスタント",
        "AI 사용 도우미",
        "Trợ lý sử dụng AI",
        "Ваш помощник для ИИ",
        "دستیار استفاده از هوش مصنوعی",
    ],
    title: [
        "让 AI 工具，更顺畅地工作。",
        "讓 AI 工具，更順暢地工作。",
        "Less setup. More time with AI.",
        "AIツールを、もっと快適に。",
        "AI 도구를 더 편리하게.",
        "Dùng AI thuận tiện hơn.",
        "Меньше настройки. Больше ИИ.",
        "تنظیم ساده‌تر، استفاده روان‌تر از هوش مصنوعی.",
    ],
    intro: [
        "从 AI 应用的网络配置，到电脑与手机的使用指引。把繁琐步骤整理清楚，让你专注于工作、学习和创作。",
        "從 AI 應用的網路設定，到電腦與手機的使用指引。整理繁瑣步驟，讓你專注工作、學習和創作。",
        "Clear guidance for AI app connectivity, desktop and mobile setup. Spend less time configuring and more time working, learning and creating.",
        "AIアプリの接続設定からPC・スマートフォンでの使い方まで。設定をシンプルにし、仕事や学習、創作に集中しましょう。",
        "AI 앱 연결 설정부터 PC와 모바일 사용 안내까지. 설정에 쓰는 시간을 줄이고 업무, 학습과 창작에 집중하세요.",
        "Hướng dẫn kết nối ứng dụng AI và thiết lập trên máy tính, điện thoại. Dành ít thời gian cấu hình hơn và tập trung vào công việc, học tập, sáng tạo.",
        "Понятные инструкции по подключению ИИ-приложений на компьютере и телефоне. Меньше настройки — больше работы, учёбы и творчества.",
        "راهنمای روشن برای اتصال برنامه‌های هوش مصنوعی و تنظیم رایانه و گوشی؛ روی کار، یادگیری و خلق کردن تمرکز کنید.",
    ],
    seeDemo: [
        "了解配置步骤",
        "了解設定步驟",
        "See the setup steps",
        "設定手順を見る",
        "설정 단계 보기",
        "Xem các bước thiết lập",
        "Посмотреть шаги",
        "مشاهده مراحل تنظیم",
    ],
    setupTitle: [
        "三步，整理好你的使用环境。",
        "三步，整理好你的使用環境。",
        "Three steps to a simpler setup.",
        "3ステップで利用環境を整える。",
        "세 단계로 사용 환경 설정.",
        "Thiết lập dễ dàng trong ba bước.",
        "Три шага к удобной настройке.",
        "سه گام برای تنظیم ساده‌تر.",
    ],
    step1: [
        "选择适合的方案",
        "選擇適合的方案",
        "Choose a suitable plan",
        "自分に合うプランを選ぶ",
        "맞는 요금제 선택",
        "Chọn gói phù hợp",
        "Выберите подходящий план",
        "انتخاب طرح مناسب",
    ],
    step1Text: [
        "根据使用需求，选择套餐或独立额度。",
        "依使用需求，選擇方案或獨立額度。",
        "Choose a subscription or standalone credits for your needs.",
        "利用目的に合わせてプランや単独で使えるクレジットを選択。",
        "필요에 맞는 구독 또는 독립 사용 가능한 크레딧을 선택하세요.",
        "Chọn gói đăng ký hoặc dung lượng độc lập theo nhu cầu.",
        "Выберите подписку или отдельный запас трафика по своим потребностям.",
        "متناسب با نیازتان اشتراک یا اعتبار مستقل انتخاب کنید.",
    ],
    step2: [
        "把配置交给助手",
        "把設定交給助手",
        "Bring your setup together",
        "設定をまとめる",
        "설정 불러오기",
        "Nhập cấu hình dễ dàng",
        "Соберите настройки",
        "وارد کردن تنظیمات",
    ],
    step2Text: [
        "使用快捷导入，或按图文指引完成设置。",
        "使用快捷匯入，或依圖文指引完成設定。",
        "Use quick import or follow the illustrated guidance.",
        "クイックインポートやガイドに沿って設定。",
        "빠른 가져오기 또는 안내에 따라 설정하세요.",
        "Dùng tính năng nhập nhanh hoặc làm theo hướng dẫn.",
        "Используйте быстрый импорт или пошаговую инструкцию.",
        "از ورود سریع یا راهنمای مرحله‌ای استفاده کنید.",
    ],
    step3: [
        "开始使用 AI 工具",
        "開始使用 AI 工具",
        "Get back to your AI tools",
        "AIツールを使い始める",
        "AI 도구 사용 시작",
        "Bắt đầu sử dụng AI",
        "Начните пользоваться ИИ",
        "شروع استفاده از ابزارهای هوش مصنوعی",
    ],
    step3Text: [
        "遇到配置问题，在帮助中心找到解答。",
        "遇到設定問題，在說明中心找到解答。",
        "Find answers to setup questions in the help center.",
        "設定で困ったときはヘルプセンターへ。",
        "설정 문제가 생기면 도움말 센터를 확인하세요.",
        "Tìm câu trả lời cho vấn đề thiết lập trong trung tâm trợ giúp.",
        "Ответы на вопросы настройки — в центре помощи.",
        "پاسخ پرسش‌های تنظیم را در مرکز راهنما پیدا کنید.",
    ],
    approachTitle: [
        "少一点折腾，多一点专注。",
        "少一點折騰，多一點專注。",
        "More focus. Less friction.",
        "手間を減らし、集中を増やす。",
        "설정은 간단하게, 집중은 더 많이.",
        "Ít thao tác hơn, tập trung hơn.",
        "Меньше хлопот. Больше внимания делу.",
        "دردسر کمتر، تمرکز بیشتر.",
    ],
    approachText: [
        "我们帮助你整理 AI 应用的连接与设备配置问题。清晰的使用文档、便捷的设备导入和在线支持，让每一步都更容易理解。",
        "我們協助整理 AI 應用的連線與裝置設定問題。清楚的文件、便利的裝置匯入與線上支援，讓每一步更易理解。",
        "We help with connectivity and device setup for AI apps. Clear documentation, convenient imports and online support make each step easier to understand.",
        "AIアプリの接続やデバイス設定をサポート。わかりやすい文書、簡単なインポート、オンラインサポートを提供します。",
        "AI 앱 연결 및 기기 설정을 돕습니다. 명확한 문서, 간편한 가져오기와 온라인 지원으로 각 단계를 이해하기 쉽게 안내합니다.",
        "Chúng tôi hỗ trợ kết nối và thiết lập thiết bị cho ứng dụng AI bằng tài liệu rõ ràng, nhập cấu hình thuận tiện và hỗ trợ trực tuyến.",
        "Помогаем с подключением и настройкой устройств для ИИ: понятная документация, удобный импорт и онлайн-поддержка.",
        "برای اتصال و تنظیم دستگاه‌های برنامه‌های هوش مصنوعی، مستندات روشن، ورود آسان تنظیمات و پشتیبانی آنلاین فراهم می‌کنیم.",
    ],
    q1: [
        "这是一个 AI 聊天工具吗？",
        "這是 AI 聊天工具嗎？",
        "Is this an AI chat tool?",
        "AIチャットツールですか？",
        "AI 채팅 도구인가요?",
        "Đây có phải công cụ trò chuyện AI không?",
        "Это ИИ-чат?",
        "آیا این ابزار گفت‌وگو با هوش مصنوعی است؟",
    ],
    a1: [
        "这里主要提供 AI 应用的使用环境配置与帮助。进入工作台后，你可以管理设备配置、查看使用文档和获取支持。",
        "這裡主要提供 AI 應用的使用環境設定與協助。進入工作台後，可管理裝置設定、查看文件並取得支援。",
        "This workspace focuses on setup and guidance for using AI apps. Manage device configuration, read documentation and get support.",
        "AIアプリを使うための環境設定とガイドを提供します。設定の管理、文書の閲覧、サポートへの相談ができます。",
        "AI 앱 사용을 위한 환경 설정과 안내를 제공합니다. 기기 설정을 관리하고 문서를 읽거나 지원을 요청할 수 있습니다.",
        "Không gian này hỗ trợ thiết lập môi trường sử dụng AI. Bạn có thể quản lý cấu hình thiết bị, đọc tài liệu và yêu cầu hỗ trợ.",
        "Здесь можно настроить среду для ИИ-приложений, управлять конфигурацией устройств, читать инструкции и обращаться за помощью.",
        "این فضا برای تنظیم محیط استفاده از برنامه‌های هوش مصنوعی و راهنمایی است؛ تنظیم دستگاه، مستندات و پشتیبانی در دسترس است.",
    ],
    q2: [
        "手机和电脑都可以使用吗？",
        "手機和電腦都能使用嗎？",
        "Can I use it on mobile and desktop?",
        "スマートフォンとPCで使えますか？",
        "휴대폰과 PC 모두 사용 가능한가요?",
        "Có thể dùng trên điện thoại và máy tính không?",
        "Можно использовать на телефоне и компьютере?",
        "آیا روی گوشی و رایانه کار می‌کند؟",
    ],
    a2: [
        "可以。支持 Windows、macOS、iOS 和 Android，并提供对应设备的配置指引，让你在电脑和手机上轻松开始。",
        "可以。支援 Windows、macOS、iOS 和 Android，並提供對應裝置的設定指引，讓你在電腦和手機上輕鬆開始。",
        "Yes. Windows, macOS, iOS and Android are supported, with device-specific guidance to help you get started on your computer or phone.",
        "はい。Windows、macOS、iOS、Androidに対応しています。デバイス別のガイドで、PCでもスマートフォンでも簡単に始められます。",
        "네. Windows, macOS, iOS, Android를 지원하며, 기기별 안내로 PC와 휴대폰에서 쉽게 시작할 수 있습니다.",
        "Có. Hỗ trợ Windows, macOS, iOS và Android với hướng dẫn riêng cho từng thiết bị, giúp bạn dễ dàng bắt đầu trên máy tính hoặc điện thoại.",
        "Да. Поддерживаются Windows, macOS, iOS и Android. Инструкции для каждого устройства помогут начать работу на компьютере или телефоне.",
        "بله. Windows، macOS، iOS و Android پشتیبانی می‌شوند و راهنمای هر دستگاه به شما کمک می‌کند به‌سادگی روی رایانه یا گوشی شروع کنید.",
    ],
    q3: [
        "是否包含 AI 应用的账号或会员？",
        "是否包含 AI 應用的帳號或會員？",
        "Are AI app accounts or memberships included?",
        "AIアプリのアカウントや会員資格は含まれますか？",
        "AI 앱 계정이나 멤버십이 포함되나요?",
        "Có bao gồm tài khoản hoặc gói thành viên AI không?",
        "Включены ли аккаунты или платный доступ к ИИ-приложениям?",
        "آیا حساب یا عضویت برنامه‌های هوش مصنوعی هم ارائه می‌شود؟",
    ],
    a3: [
        "本站提供使用环境配置与帮助，不包含第三方 AI 应用的账号或会员。是否需要单独注册或付费，以对应应用的说明为准。",
        "本站提供使用環境設定與協助，不包含第三方 AI 應用帳號或會員。是否需另行註冊或付費，請依該應用說明。",
        "We provide environment setup and guidance, not third-party AI accounts or memberships. Check each app for its registration and payment requirements.",
        "利用環境の設定とガイドを提供します。外部AIアプリのアカウントや会員資格は含まれません。登録や支払いの要否は各アプリでご確認ください。",
        "사용 환경 설정과 안내를 제공하며 외부 AI 앱 계정이나 멤버십은 포함되지 않습니다. 별도 가입이나 결제 요건은 각 앱에서 확인하세요.",
        "Trang cung cấp thiết lập môi trường và hướng dẫn, không bao gồm tài khoản hay gói thành viên AI bên thứ ba. Xem yêu cầu đăng ký và thanh toán của từng ứng dụng.",
        "Мы помогаем настроить среду, но не предоставляем аккаунты или членство в сторонних ИИ-приложениях. Условия регистрации и оплаты уточняйте в самих приложениях.",
        "ما تنظیم محیط و راهنمایی ارائه می‌کنیم، نه حساب یا عضویت برنامه‌های شخص ثالث. شرایط ثبت‌نام و پرداخت را در هر برنامه بررسی کنید.",
    ],
    q4: [
        "遇到问题，在哪里查看帮助？",
        "遇到問題，在哪裡查看協助？",
        "Where can I find help?",
        "困ったときはどこで確認できますか？",
        "문제가 생기면 어디서 도움을 받나요?",
        "Có thể tìm trợ giúp ở đâu?",
        "Где найти помощь?",
        "از کجا راهنمایی بگیرم؟",
    ],
    a4: [
        "登录后打开「帮助中心」，按问题分类查看常见解答，或搜索使用文档。仍未解决时，可从页面下方联系支持；已有咨询请继续回复，方便追踪进展。",
        "登入後開啟「說明中心」，依分類查看常見解答，或搜尋使用文件。仍未解決時，可從頁面下方聯絡支援；已有諮詢請繼續回覆，以便追蹤進度。",
        "After signing in, open Help Center to browse common answers or search the documentation. If you still need help, contact support at the bottom of the page. Continue an existing conversation to keep progress together.",
        "ログイン後、ヘルプセンターで分類別の回答やドキュメントを検索できます。解決しない場合はページ下部からお問い合わせください。既存の問い合わせに返信すると経緯をまとめられます。",
        "로그인 후 도움말 센터에서 분류별 답변이나 문서를 검색하세요. 해결되지 않으면 페이지 아래에서 지원에 문의하세요. 기존 문의에 이어서 답장하면 진행 내용을 함께 확인할 수 있습니다.",
        "Sau khi đăng nhập, mở Trung tâm trợ giúp để xem câu trả lời theo nhóm hoặc tìm tài liệu. Nếu chưa giải quyết được, liên hệ hỗ trợ ở cuối trang. Tiếp tục trao đổi cũ để tiện theo dõi.",
        "После входа откройте справку, выберите категорию или найдите инструкцию. Если вопрос остался, обратитесь в поддержку внизу страницы. Продолжайте существующий диалог, чтобы сохранить историю.",
        "پس از ورود، مرکز راهنما را باز کنید و پاسخ‌های دسته‌بندی‌شده یا مستندات را جست‌وجو کنید. اگر مشکل حل نشد، از پایین صفحه با پشتیبانی تماس بگیرید و گفت‌وگوی قبلی را ادامه دهید تا روند مشخص بماند.",
    ],
    footer: [
        "为每一次更顺畅的 AI 使用体验。",
        "為每一次更順暢的 AI 使用體驗。",
        "For a smoother experience with AI.",
        "AIをもっと快適に使うために。",
        "더 편리한 AI 사용을 위해.",
        "Cho trải nghiệm AI thuận tiện hơn.",
        "Для удобной работы с ИИ.",
        "برای تجربه روان‌تر با هوش مصنوعی.",
    ],
} as const;
[
    "zh-CN",
    "zh-TW",
    "en-US",
    "ja-JP",
    "ko-KR",
    "vi-VN",
    "ru-RU",
    "fa-IR",
].forEach((code, index) =>
    i18n.addResourceBundle(
        code,
        "landing",
        Object.fromEntries(
            Object.entries(landingCopy).map(([key, values]) => [
                key,
                values[index],
            ]),
        ),
    ),
);
