import i18n from "./i18n";
export const landingCopy = {
    skip: [
        "跳转到主要内容",
        "跳至主要內容",
        "Skip to content",
        "本文へ移動",
        "본문으로 건너뛰기",
        "Chuyển đến nội dung",
        "Перейти к содержимому",
        "رفتن به محتوا",
    ],
    preview: [
        "配置预览",
        "設定預覽",
        "Setup preview",
        "設定プレビュー",
        "설정 미리보기",
        "Xem trước thiết lập",
        "Предпросмотр настройки",
        "پیش‌نمایش تنظیم",
    ],
    previewNote: [
        "登录后，按设备获取完整配置指引。",
        "登入後，依裝置取得完整設定指引。",
        "Sign in for the complete setup guide for your device.",
        "ログインしてデバイスに合った設定ガイドを確認。",
        "로그인하여 기기에 맞는 전체 설정 안내를 확인하세요.",
        "Đăng nhập để xem hướng dẫn đầy đủ cho thiết bị của bạn.",
        "Войдите, чтобы получить полную инструкцию для устройства.",
        "برای راهنمای کامل تنظیم دستگاه خود وارد شوید.",
    ],
    beforeStart: [
        "开始之前",
        "開始之前",
        "Before you begin",
        "はじめる前に",
        "시작하기 전에",
        "Trước khi bắt đầu",
        "Перед началом",
        "پیش از شروع",
    ],
    terms: [
        "服务条款",
        "服務條款",
        "Terms of service",
        "利用規約",
        "이용약관",
        "Điều khoản dịch vụ",
        "Условия использования",
        "شرایط استفاده",
    ],
    examples: [
        "配置流程",
        "設定流程",
        "How it works",
        "設定の流れ",
        "설정 과정",
        "Cách thiết lập",
        "Как это работает",
        "روش راه‌اندازی",
    ],
    about: [
        "使用帮助",
        "使用協助",
        "How we help",
        "使い方のサポート",
        "사용 지원",
        "Hỗ trợ sử dụng",
        "Помощь",
        "راهنمای استفاده",
    ],
    questions: [
        "常见问题",
        "常見問題",
        "Questions",
        "よくある質問",
        "자주 묻는 질문",
        "Câu hỏi",
        "Вопросы",
        "پرسش‌ها",
    ],
    signIn: [
        "登录",
        "登入",
        "Sign in",
        "ログイン",
        "로그인",
        "Đăng nhập",
        "Войти",
        "ورود",
    ],
    start: [
        "开始配置",
        "開始設定",
        "Start your setup",
        "設定を始める",
        "설정 시작",
        "Bắt đầu thiết lập",
        "Начать настройку",
        "شروع تنظیم",
    ],
    tag: [
        "你的 AI 使用助手",
        "你的 AI 使用助手",
        "Your AI setup companion",
        "AIの利用を支えるアシスタント",
        "AI 사용 도우미",
        "Trợ lý sử dụng AI",
        "Ваш помощник для ИИ",
        "دستیار استفاده از هوش مصنوعی",
    ],
    title: [
        "让 AI 工具，更顺畅地工作。",
        "讓 AI 工具，更順暢地工作。",
        "Less setup. More time with AI.",
        "AIツールを、もっと快適に。",
        "AI 도구를 더 편리하게.",
        "Dùng AI thuận tiện hơn.",
        "Меньше настройки. Больше ИИ.",
        "تنظیم ساده‌تر، استفاده روان‌تر از هوش مصنوعی.",
    ],
    intro: [
        "从 AI 应用的网络配置，到电脑与手机的使用指引。把繁琐步骤整理清楚，让你专注于工作、学习和创作。",
        "從 AI 應用的網路設定，到電腦與手機的使用指引。整理繁瑣步驟，讓你專注工作、學習和創作。",
        "Clear guidance for AI app connectivity, desktop and mobile setup. Spend less time configuring and more time working, learning and creating.",
        "AIアプリの接続設定からPC・スマートフォンでの使い方まで。設定をシンプルにし、仕事や学習、創作に集中しましょう。",
        "AI 앱 연결 설정부터 PC와 모바일 사용 안내까지. 설정에 쓰는 시간을 줄이고 업무, 학습과 창작에 집중하세요.",
        "Hướng dẫn kết nối ứng dụng AI và thiết lập trên máy tính, điện thoại. Dành ít thời gian cấu hình hơn và tập trung vào công việc, học tập, sáng tạo.",
        "Понятные инструкции по подключению ИИ-приложений на компьютере и телефоне. Меньше настройки — больше работы, учёбы и творчества.",
        "راهنمای روشن برای اتصال برنامه‌های هوش مصنوعی و تنظیم رایانه و گوشی؛ روی کار، یادگیری و خلق کردن تمرکز کنید.",
    ],
    seeDemo: [
        "了解配置步骤",
        "了解設定步驟",
        "See the setup steps",
        "設定手順を見る",
        "설정 단계 보기",
        "Xem các bước thiết lập",
        "Посмотреть шаги",
        "مشاهده مراحل تنظیم",
    ],
    setupTitle: [
        "三步，整理好你的使用环境。",
        "三步，整理好你的使用環境。",
        "Three steps to a simpler setup.",
        "3ステップで利用環境を整える。",
        "세 단계로 사용 환경 설정.",
        "Thiết lập dễ dàng trong ba bước.",
        "Три шага к удобной настройке.",
        "سه گام برای تنظیم ساده‌تر.",
    ],
    step1: [
        "选择你的设备",
        "選擇你的裝置",
        "Choose your device",
        "デバイスを選ぶ",
        "기기 선택",
        "Chọn thiết bị",
        "Выберите устройство",
        "انتخاب دستگاه",
    ],
    step1Text: [
        "按电脑或手机，找到适合的配置方式。",
        "依電腦或手機，找到適合的設定方式。",
        "Find setup options suited to your computer or phone.",
        "PCやスマートフォンに合う設定方法を確認。",
        "PC나 휴대폰에 맞는 설정 방법을 찾으세요.",
        "Tìm cách thiết lập phù hợp cho máy tính hoặc điện thoại.",
        "Найдите способ настройки для компьютера или телефона.",
        "روش مناسب برای رایانه یا گوشی خود را پیدا کنید.",
    ],
    step2: [
        "把配置交给助手",
        "把設定交給助手",
        "Bring your setup together",
        "設定をまとめる",
        "설정 불러오기",
        "Nhập cấu hình dễ dàng",
        "Соберите настройки",
        "وارد کردن تنظیمات",
    ],
    step2Text: [
        "使用快捷导入，或按图文指引完成设置。",
        "使用快捷匯入，或依圖文指引完成設定。",
        "Use quick import or follow the illustrated guidance.",
        "クイックインポートやガイドに沿って設定。",
        "빠른 가져오기 또는 안내에 따라 설정하세요.",
        "Dùng tính năng nhập nhanh hoặc làm theo hướng dẫn.",
        "Используйте быстрый импорт или пошаговую инструкцию.",
        "از ورود سریع یا راهنمای مرحله‌ای استفاده کنید.",
    ],
    step3: [
        "开始使用 AI 工具",
        "開始使用 AI 工具",
        "Get back to your AI tools",
        "AIツールを使い始める",
        "AI 도구 사용 시작",
        "Bắt đầu sử dụng AI",
        "Начните пользоваться ИИ",
        "شروع استفاده از ابزارهای هوش مصنوعی",
    ],
    step3Text: [
        "遇到配置问题，在帮助中心找到解答。",
        "遇到設定問題，在說明中心找到解答。",
        "Find answers to setup questions in the help center.",
        "設定で困ったときはヘルプセンターへ。",
        "설정 문제가 생기면 도움말 센터를 확인하세요.",
        "Tìm câu trả lời cho vấn đề thiết lập trong trung tâm trợ giúp.",
        "Ответы на вопросы настройки — в центре помощи.",
        "پاسخ پرسش‌های تنظیم را در مرکز راهنما پیدا کنید.",
    ],
    approachTitle: [
        "少一点折腾，多一点专注。",
        "少一點折騰，多一點專注。",
        "More focus. Less friction.",
        "手間を減らし、集中を増やす。",
        "설정은 간단하게, 집중은 더 많이.",
        "Ít thao tác hơn, tập trung hơn.",
        "Меньше хлопот. Больше внимания делу.",
        "دردسر کمتر، تمرکز بیشتر.",
    ],
    approachText: [
        "我们帮助你整理 AI 应用的连接与设备配置问题。清晰的使用文档、便捷的设备导入和在线支持，让每一步都更容易理解。",
        "我們協助整理 AI 應用的連線與裝置設定問題。清楚的文件、便利的裝置匯入與線上支援，讓每一步更易理解。",
        "We help with connectivity and device setup for AI apps. Clear documentation, convenient imports and online support make each step easier to understand.",
        "AIアプリの接続やデバイス設定をサポート。わかりやすい文書、簡単なインポート、オンラインサポートを提供します。",
        "AI 앱 연결 및 기기 설정을 돕습니다. 명확한 문서, 간편한 가져오기와 온라인 지원으로 각 단계를 이해하기 쉽게 안내합니다.",
        "Chúng tôi hỗ trợ kết nối và thiết lập thiết bị cho ứng dụng AI bằng tài liệu rõ ràng, nhập cấu hình thuận tiện và hỗ trợ trực tuyến.",
        "Помогаем с подключением и настройкой устройств для ИИ: понятная документация, удобный импорт и онлайн-поддержка.",
        "برای اتصال و تنظیم دستگاه‌های برنامه‌های هوش مصنوعی، مستندات روشن، ورود آسان تنظیمات و پشتیبانی آنلاین فراهم می‌کنیم.",
    ],
    q1: [
        "这是一个 AI 聊天工具吗？",
        "這是 AI 聊天工具嗎？",
        "Is this an AI chat tool?",
        "AIチャットツールですか？",
        "AI 채팅 도구인가요?",
        "Đây có phải công cụ trò chuyện AI không?",
        "Это ИИ-чат?",
        "آیا این ابزار گفت‌وگو با هوش مصنوعی است؟",
    ],
    a1: [
        "这里主要提供 AI 应用的使用环境配置与帮助。进入工作台后，你可以管理设备配置、查看使用文档和获取支持。",
        "這裡主要提供 AI 應用的使用環境設定與協助。進入工作台後，可管理裝置設定、查看文件並取得支援。",
        "This workspace focuses on setup and guidance for using AI apps. Manage device configuration, read documentation and get support.",
        "AIアプリを使うための環境設定とガイドを提供します。設定の管理、文書の閲覧、サポートへの相談ができます。",
        "AI 앱 사용을 위한 환경 설정과 안내를 제공합니다. 기기 설정을 관리하고 문서를 읽거나 지원을 요청할 수 있습니다.",
        "Không gian này hỗ trợ thiết lập môi trường sử dụng AI. Bạn có thể quản lý cấu hình thiết bị, đọc tài liệu và yêu cầu hỗ trợ.",
        "Здесь можно настроить среду для ИИ-приложений, управлять конфигурацией устройств, читать инструкции и обращаться за помощью.",
        "این فضا برای تنظیم محیط استفاده از برنامه‌های هوش مصنوعی و راهنمایی است؛ تنظیم دستگاه، مستندات و پشتیبانی در دسترس است.",
    ],
    q2: [
        "手机和电脑都可以使用吗？",
        "手機和電腦都能使用嗎？",
        "Can I use it on mobile and desktop?",
        "スマートフォンとPCで使えますか？",
        "휴대폰과 PC 모두 사용 가능한가요?",
        "Có thể dùng trên điện thoại và máy tính không?",
        "Можно использовать на телефоне и компьютере?",
        "آیا روی گوشی و رایانه کار می‌کند؟",
    ],
    a2: [
        "可以。界面适配手机与电脑，并按设备推荐配置方式。微信、QQ、微博内打开时，请使用手机自带浏览器以完成配置操作。",
        "可以。介面適配手機與電腦，並依裝置推薦設定方式。從微信、QQ、微博開啟時，請改用手機瀏覽器完成設定。",
        "Yes. The interface adapts to phones and computers with device-specific setup suggestions. From WeChat, QQ or Weibo, open the page in your phone’s browser.",
        "はい。スマートフォンとPCに対応し、デバイスに合う方法を提案します。WeChat、QQ、Weiboでは標準ブラウザで開いてください。",
        "네. 휴대폰과 PC에 맞게 표시하고 기기에 맞는 설정을 추천합니다. WeChat, QQ, Weibo에서는 기본 브라우저로 여세요.",
        "Có. Giao diện phù hợp cho điện thoại và máy tính. Khi mở từ WeChat, QQ hoặc Weibo, hãy dùng trình duyệt trên điện thoại.",
        "Да. Интерфейс адаптирован для телефона и компьютера. Из WeChat, QQ или Weibo открывайте страницу в браузере телефона.",
        "بله. رابط برای گوشی و رایانه سازگار است. از WeChat، QQ یا Weibo صفحه را در مرورگر گوشی باز کنید.",
    ],
    footer: [
        "为每一次更顺畅的 AI 使用体验。",
        "為每一次更順暢的 AI 使用體驗。",
        "For a smoother experience with AI.",
        "AIをもっと快適に使うために。",
        "더 편리한 AI 사용을 위해.",
        "Cho trải nghiệm AI thuận tiện hơn.",
        "Для удобной работы с ИИ.",
        "برای تجربه روان‌تر با هوش مصنوعی.",
    ],
} as const;
[
    "zh-CN",
    "zh-TW",
    "en-US",
    "ja-JP",
    "ko-KR",
    "vi-VN",
    "ru-RU",
    "fa-IR",
].forEach((code, index) =>
    i18n.addResourceBundle(
        code,
        "landing",
        Object.fromEntries(
            Object.entries(landingCopy).map(([key, values]) => [
                key,
                values[index],
            ]),
        ),
    ),
);
