import i18n, { languages } from "./i18n";
const copy = {
    replaceHint: [
        "也可重新选择套餐，确认后替换待支付订单。",
        "也可重新選擇方案，確認後替換待付款訂單。",
        "You can choose another plan and replace this unpaid order at confirmation.",
        "別のプランを選び、確定時に未払い注文を置き換えられます。",
        "다른 요금제를 선택하고 확인 시 미결제 주문을 교체할 수 있습니다.",
        "Bạn có thể chọn gói khác và thay đơn chưa thanh toán khi xác nhận.",
        "Можно выбрать другой план и заменить неоплаченный заказ при подтверждении.",
        "می‌توانید طرح دیگری انتخاب و هنگام تأیید، سفارش پرداخت‌نشده را جایگزین کنید.",
    ],
    replaceConfirm: [
        "继续将取消原待支付订单，返还的余额用于新订单；创建失败则保留原订单。",
        "繼續將取消原待付款訂單，退回餘額用於新訂單；建立失敗則保留原訂單。",
        "Continuing replaces the unpaid order and applies its returned balance. If creation fails, the original order is kept.",
        "続行すると未払い注文を取り消し、返還残高を新注文に適用します。作成失敗時は元の注文を保持します。",
        "계속하면 기존 미결제 주문을 취소하고 반환 잔액을 새 주문에 적용합니다. 생성 실패 시 기존 주문이 유지됩니다.",
        "Tiếp tục sẽ hủy đơn chưa thanh toán và dùng số dư hoàn lại cho đơn mới. Nếu tạo thất bại, đơn cũ được giữ nguyên.",
        "Продолжение отменит неоплаченный заказ и применит возвращённый баланс к новому. При ошибке старый заказ сохранится.",
        "با ادامه، سفارش پرداخت‌نشده لغو و موجودی برگشتی به سفارش جدید اعمال می‌شود. در صورت خطا، سفارش قبلی حفظ می‌شود.",
    ],
    subscribe: [
        "订阅",
        "訂閱",
        "Subscribe",
        "申し込む",
        "구독",
        "Đăng ký",
        "Подписаться",
        "اشتراک",
    ],
    renew: [
        "续费",
        "續費",
        "Renew",
        "更新する",
        "갱신",
        "Gia hạn",
        "Продлить",
        "تمدید",
    ],
    switchPlan: [
        "切换套餐",
        "切換方案",
        "Switch plan",
        "プランを変更",
        "요금제 변경",
        "Đổi gói",
        "Сменить план",
        "تغییر طرح",
    ],
    resubscribe: [
        "重新订阅",
        "重新訂閱",
        "Resubscribe",
        "再契約",
        "다시 구독",
        "Đăng ký lại",
        "Подписаться снова",
        "اشتراک مجدد",
    ],
    previousPlan: [
        "原套餐",
        "原方案",
        "Previous plan",
        "以前のプラン",
        "이전 요금제",
        "Gói trước",
        "Предыдущий план",
        "طرح قبلی",
    ],
    actionTitle: [
        "{{action}} · {{plan}}",
        "{{action}} · {{plan}}",
        "{{action}} · {{plan}}",
        "{{action}} · {{plan}}",
        "{{action}} · {{plan}}",
        "{{action}} · {{plan}}",
        "{{action}} · {{plan}}",
        "{{action}} · {{plan}}",
    ],
    feeDetails: [
        "费用说明",
        "費用說明",
        "Pricing details",
        "料金について",
        "요금 안내",
        "Chi tiết chi phí",
        "Подробнее об оплате",
        "جزئیات هزینه",
    ],
    month: ["月", "月", "month", "月", "월", "tháng", "мес.", "ماه"],
    year: ["年", "年", "year", "年", "년", "năm", "год", "سال"],
    equivalent: [
        "约 {{price}} / 月",
        "約 {{price}} / 月",
        "≈ {{price}} / month",
        "約 {{price}} / 月",
        "약 {{price}} / 월",
        "≈ {{price}} / tháng",
        "≈ {{price}} / мес.",
        "حدود {{price}} / ماه",
    ],
    savingBadge: [
        "省 {{percent}}%",
        "省 {{percent}}%",
        "Save {{percent}}%",
        "{{percent}}% お得",
        "{{percent}}% 절약",
        "Tiết kiệm {{percent}}%",
        "−{{percent}}%",
        "{{percent}}٪ تخفیف",
    ],
    annual: [
        "折合 {{price}} / 月，按年一次支付",
        "折合 {{price}} / 月，按年一次支付",
        "Equivalent to {{price}} / month, billed annually",
        "月額換算 {{price}}、年額一括払い",
        "월 환산 {{price}}, 연간 일시 결제",
        "Tương đương {{price}} / tháng, thanh toán theo năm",
        "Эквивалент {{price}} / мес., оплата за год",
        "معادل {{price}} در ماه، پرداخت سالانه",
    ],
    total: [
        "按所选周期一次支付",
        "按所選週期一次支付",
        "One payment for the selected period",
        "選択した期間の一括払い",
        "선택한 기간 요금 일시 결제",
        "Thanh toán một lần cho kỳ đã chọn",
        "Разовая оплата выбранного периода",
        "پرداخت یکجای دوره انتخاب‌شده",
    ],
    save: [
        "比逐月支付节省 {{percent}}%",
        "比逐月支付節省 {{percent}}%",
        "Save {{percent}}% vs. monthly payments",
        "月払い比 {{percent}}% お得",
        "매월 결제 대비 {{percent}}% 절약",
        "Tiết kiệm {{percent}}% so với trả hàng tháng",
        "На {{percent}}% дешевле ежемесячной оплаты",
        "{{percent}}٪ صرفه‌جویی نسبت به پرداخت ماهانه",
    ],
    fallback: [
        "此套餐提供{{period}}，可查看其他周期",
        "此套餐提供{{period}}，可查看其他週期",
        "Available: {{period}}. View other periods at checkout.",
        "{{period}}に対応。他の期間は購入時に確認できます。",
        "{{period}} 가능. 결제 시 다른 기간을 확인하세요.",
        "Có kỳ {{period}}. Xem kỳ khác khi thanh toán.",
        "Доступно: {{period}}. Другие периоды — при оформлении.",
        "موجود: {{period}}. دوره‌های دیگر را هنگام خرید ببینید.",
    ],
};
languages.forEach((language, index) =>
    i18n.addResourceBundle(
        language.code,
        "pricing",
        Object.fromEntries(
            Object.entries(copy).map(([key, values]) => [key, values[index]]),
        ),
    ),
);
export const pricingCopy = (
    key: keyof typeof copy,
    args: Record<string, unknown> = {},
): string => String(i18n.t(key, { ns: "pricing", ...args }));
